apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-binpack-scheduler-config
  namespace: kube-system
data:
  gpu-binpack-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
      #clientConnection:
      #kubeconfig: "/etc/kubernetes/scheduler.conf"
      #acceptContentTypes: "application/yaml"
      #contentType: "application/yaml"
    leaderElection:
      leaderElect: false
      resourceNamespace: kube-system
      resourceName: gpu-binpack-scheduler
      leaseDuration: 15s
      renewDeadline: 10s
    profiles:
    - pluginConfig:
      - args:
          scoringStrategy:
            resources:
            - name: cpu
              weight: 1
            - name: memory
              weight: 1
            - name: nvidia.com/gpu
              weight: 3
            type: MostAllocated
        name: NodeResourcesFit
      schedulerName: gpu-binpack-scheduler
