{{- if .Values.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-prometheus-0
  annotations:
    helm.sh/resource-policy: keep
spec:
  capacity:
    storage: {{ .Values.size | quote }}
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    {{- range .Values.accessModes }}
    - {{ . | quote }}
    {{- end }}
  storageClassName: {{ .Values.storageClassName }}
  local:
    path: {{ .Values.basePath }}/prometheus-volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.nodeName }}
{{- end }}
