all:
  children:
    calico-rr:
      hosts: {}
    etcd:
      hosts:
        master-01: null
    k8s-cluster:
      children:
        kube-master:
          hosts: {}
        kube-node:
          hosts: {}
    kube-master:
      hosts:
        master-01: null
    kube-node:
      hosts:
        worker-01: null
  hosts:
    master-01:
      ansible_host: 192.168.1.10
      ip: 192.168.1.10
      access_ip: 192.168.1.10
    worker-01:
      ansible_host: 192.168.1.11
      ip: 192.168.1.11
      access_ip: 192.168.1.11
