all:
  hosts:
    master-1:
      ansible_host: 10.61.3.91
      ip: 10.61.3.91
      access_ip: 10.61.3.91
    worker-1:
      ansible_host: 10.61.3.92
      ip: 10.61.3.92
      access_ip: 10.61.3.92
    worker-2:
      ansible_host: 10.61.3.93
      ip: 10.61.3.93
      access_ip: 10.61.3.93
  children:
    kube_control_plane:
      hosts:
        master-1:
    kube_node:
      hosts:
        worker-1:
        worker-2:
    etcd:
      hosts:
        master-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
