apiVersion: apps/v1
kind: Deployment
metadata:
  name: astrago-nginx
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: "{{ default .Values.proxy.image.registry .Values.global.imageRegistry }}/{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}"          
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config-volume
          configMap:
            name: astrago-nginx-config
