#repositories:
#- name: csi-driver-nfs
#  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
#- name: volcano-sh 
#  url: https://volcano-sh.github.io/helm-charts
#- name: fluxcd-community
#  url: fluxcd-community https://fluxcd-community.github.io/helm-charts
#- name: nvidia
#  url: https://nvidia.github.io/gpu-operator
#- name: grafana
#  url: https://grafana.github.io/helm-charts
#- name: prometheus-community
#  url: https://prometheus-community.github.io/helm-charts
#- name: keycloak
#  url: oci://registry-1.docker.io/bitnamicharts/keycloak
#- name: kubeflow
#  url: https://kubeflow.github.io/helm-charts
#- name: harbor
#  url: https://helm.goharbor.io

environments:
  prod:
    values:
    - environments/common/values.yaml
    - environments/prod/values.yaml
  dev:
    values:
    - environments/common/values.yaml
    - environments/dev/values.yaml
  dev2:
    values:
    - environments/common/values.yaml
    - environments/dev2/values.yaml
  stage:
    values:
    - environments/common/values.yaml
    - environments/stage/values.yaml
  astrago:
    values:
    - environments/common/values.yaml
    - environments/astrago/values.yaml

helmDefaults:
  wait: true
  waitForJobs: true
  timeout: 600

releases:
- name: nfs-provisioner
  namespace: nfs-provisioner
  chart: applications/csi-driver-nfs
  wait: true
  labels:
    app: nfs-provisioner
  values:
  - configs/values/csi-driver-nfs/values.yaml.gotmpl

- name: gpu-operator
  namespace: gpu-operator
  chart: applications/gpu-operator
  wait: true
  labels:
    app: gpu-operator
    type: infra
  values:
  - configs/values/gpu-operator/values.yaml.gotmpl

- name: gpu-operator-extras
  namespace: gpu-operator
  chart: applications/gpu-operator-extras
  wait: true
  labels:
    app: gpu-operator
    type: infra

- name: gpu-process-exporter
  chart: applications/gpu-process-exporter
  namespace: gpu-operator
  labels:
    app: gpu-process-exporter
  values:
  - configs/values/gpu-process-exporter/values.yaml.gotmpl

- name: volcano
  namespace: volcano-system
  createNamespace: true
  chart: applications/volcano
  version: 1.12.1
  labels:
    app: volcano
  values:
  - configs/values/volcano/values.yaml

- name: volcano-vgpu-device-plugin
  namespace: volcano-system
  createNamespace: true
  chart: applications/volcano-vgpu-device-plugin
  version: 1.0.0
  labels:
    app: volcano

- name: flux
  namespace: flux
  chart: applications/flux2
  wait: true
  labels:
    app: flux
  values:
  - configs/values/flux/values.yaml.gotmpl

- name: loki-stack
  namespace: loki-stack
  chart: applications/loki-stack
  wait: true
  labels:
    app: loki-stack
    component: logging
  values:
  - configs/values/loki-stack/values.yaml.gotmpl

- name: prometheus
  namespace: prometheus
  chart: applications/kube-prometheus-stack
  wait: true
  labels:
    app: prometheus
  values:
  - configs/values/kube-prometheus-stack/values.yaml.gotmpl

- name: keycloak
  namespace: keycloak
  # chart: oci://registry-1.docker.io/bitnamicharts/keycloak
  chart: applications/keycloak
  wait: true
  labels:
    app: keycloak
  values:
  - configs/values/keycloak/values.yaml.gotmpl

- name: keycloak-extras
  namespace: keycloak
  chart: applications/keycloak-extras
  wait: true
  labels:
    app: keycloak

- name: mpi-operator
  chart: applications/mpi-operator
  wait: true
  labels:
    app: mpi-operator
  values:
  - configs/values/mpi-operator/values.yaml.gotmpl

- name: harbor
  namespace: harbor
  chart: applications/harbor
  wait: true
  condition: harbor.enabled
  labels:
    app: harbor
  values:
  - configs/values/harbor/values.yaml.gotmpl

- name: astrago
  namespace: astrago
  chart: applications/astrago
  wait: true
  timeout: 600
  labels:
    app: astrago
  values:
  - configs/values/astrago/values.yaml.gotmpl
