environments:
  dev:
    values:
      - environments/dev.yaml
  stag:
    values:
      - environments/stg.yaml

helmDefaults:
  wait: true
  waitForJobs: true
  timeout: 600

helmfiles:
  - path: applications/uyuni/helmfile.yaml
    values:
      - { { toYaml .Values | nindent 4 } }
