#repositories:
#- name: csi-driver-nfs
#  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
#- name: volcano-sh 
#  url: https://volcano-sh.github.io/helm-charts
#- name: fluxcd-community
#  url: fluxcd-community https://fluxcd-community.github.io/helm-charts
#- name: nvidia
#  url: https://nvidia.github.io/gpu-operator

environments:
  prod:
    values:
    - environments/common/values.yaml
    - environments/prod/values.yaml
  dev:
    values:
    - environments/common/values.yaml
    - environments/dev/values.yaml
  dev2:
    values:
    - environments/common/values.yaml
    - environments/dev2/values.yaml
  stage:
    values:
    - environments/common/values.yaml
    - environments/stage/values.yaml
  astrago:
    values:
    - environments/common/values.yaml
    - environments/astrago/values.yaml

helmDefaults:
  wait: true
  waitForJobs: true
  timeout: 600

helmfiles:
- path: applications/loki-stack/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/prometheus/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/keycloak/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/mpi-operator/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/astrago/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/harbor/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

releases:
- name: nfs-provisioner
  namespace: nfs-provisioner
  chart: applications/csi-driver-nfs
  wait: true
  labels:
    app: nfs-provisioner
  values:
  - configs/values/csi-driver-nfs/values.yaml.gotmpl

- name: gpu-operator
  namespace: gpu-operator
  chart: applications/gpu-operator
  wait: true
  labels:
    app: gpu-operator
    type: infra
  values:
  - configs/values/gpu-operator/values.yaml.gotmpl

- name: gpu-operator-extras
  namespace: gpu-operator
  chart: applications/gpu-operator-extras
  wait: true
  labels:
    app: gpu-operator
    type: infra

- name: gpu-process-exporter
  chart: applications/gpu-process-exporter
  namespace: gpu-operator
  labels:
    app: gpu-process-exporter
  values:
  - configs/values/gpu-process-exporter/values.yaml.gotmpl

- name: volcano
  namespace: volcano-system
  createNamespace: true
  chart: applications/volcano
  version: 1.12.1
  labels:
    app: volcano
  values:
  - configs/values/volcano/values.yaml

- name: volcano-vgpu-device-plugin
  namespace: volcano-system
  createNamespace: true
  chart: applications/volcano-vgpu-device-plugin
  version: 1.0.0
  labels:
    app: volcano

- name: flux
  namespace: flux
  chart: applications/flux2
  wait: true
  labels:
    app: flux
  values:
  - configs/values/flux/values.yaml.gotmpl
