environments:
  default:
    values:
    - environments/default/values.yaml
  dev:
    values:
    - environments/common/values.yaml
    - environments/dev/values.yaml
  stage:
    values:
    - environments/common/values.yaml
    - environments/stage/values.yaml
  astrago:
    values:
    - environments/common/values.yaml
    - environments/astrago/values.yaml
  offline:
    values:
    - environments/common/values.yaml
    - environments/offline/values.yaml     

helmDefaults:
  wait: true
  waitForJobs: true
  timeout: 600

helmfiles:
- path: applications/csi-driver-nfs/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/gpu-operator/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/prometheus/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/keycloak/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/astrago/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}
