#repositories:
#- name: volcano-sh 
#  url: https://volcano-sh.github.io/helm-charts

environments:
  prod:
    values:
    - environments/common/values.yaml
    - environments/prod/values.yaml
  dev:
    values:
    - environments/common/values.yaml
    - environments/dev/values.yaml
  dev2:
    values:
    - environments/common/values.yaml
    - environments/dev2/values.yaml
  stage:
    values:
    - environments/common/values.yaml
    - environments/stage/values.yaml
  astrago:
    values:
    - environments/common/values.yaml
    - environments/astrago/values.yaml

helmDefaults:
  wait: true
  waitForJobs: true
  timeout: 600

helmfiles:
- path: applications/gpu-operator/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/gpu-process-exporter/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/loki-stack/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/prometheus/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/keycloak/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/mpi-operator/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/flux/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/astrago/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/harbor/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

releases:
- name: nfs-provisioner
  namespace: nfs-provisioner
  chart: applications/csi-driver-nfs
  wait: true
  labels:
    app: nfs-provisioner
  values:
  - configs/values/csi-driver-nfs/values.yaml.gotmpl

- name: volcano
  namespace: volcano-system
  createNamespace: true
  chart: applications/volcano
  version: 1.12.1
  labels:
    app: volcano
  values:
  - configs/values/volcano/values.yaml

- name: volcano-vgpu-device-plugin
  namespace: volcano-system
  createNamespace: true
  chart: applications/volcano-vgpu-device-plugin
  version: 1.0.0
  labels:
    app: volcano
