environments:
  prod:
    values:
    - environments/common/values.yaml
    - environments/prod/values.yaml
  dev:
    values:
    - environments/common/values.yaml
    - environments/dev/values.yaml
  dev2:
    values:
    - environments/common/values.yaml
    - environments/dev2/values.yaml
  stage:
    values:
    - environments/common/values.yaml
    - environments/stage/values.yaml
  astrago:
    values:
    - environments/common/values.yaml
    - environments/astrago/values.yaml

helmDefaults:
  wait: true
  waitForJobs: true
  timeout: 600

helmfiles:
- path: applications/csi-driver-nfs/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/gpu-operator/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/gpu-process-exporter/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/loki-stack/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/prometheus/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/keycloak/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

# LDAP 연동을 위한 OpenLDAP 애플리케이션 (현재 주석처리됨)
# 해당 설정은 docs/ldap-integration-work-plan.md의 "주석처리된 LDAP 관련 설정" 섹션 참조
# - path: applications/openldap/helmfile.yaml
#   values:
#   - {{ toYaml .Values | nindent 4 }}

- path: applications/mpi-operator/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/flux/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/astrago/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

- path: applications/harbor/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}
