image:
  registry: "docker.io"
  repository: "timescale/timescaledb"
  tag: "2.12.1-pg16"
  pullPolicy: IfNotPresent

auth:
  enableSuperuser: true
  superuserPassword: "timescale123!"
  database: "timescaledb"
  username: "timescale"
  password: "timescale123!"

persistence:
  enabled: true
  storageClass: "astrago-nfs-csi"
  size: "50Gi"

resources:
  limits:
    cpu: "2000m"
    memory: "4Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"

service:
  type: ClusterIP
  port: 5432

metrics:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}

config:
  sharedBuffers: "1GB"
  effectiveCacheSize: "3GB"
  maintenanceWorkMem: "256MB"
  workMem: "64MB"
  maxConnections: "200"
  maxWalSize: "4GB"
  minWalSize: "1GB"
  walBuffers: "16MB"

timescale:
  maxBackgroundWorkers: "8"
  maxChunkTime: "7d" 