apiVersion: v1
kind: ConfigMap
metadata:
  name: binpack-scheduler-config
  namespace: {{ .Release.Namespace }}
data:
  gpu-binpack-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - pluginConfig:
      - args:
          scoringStrategy:
            resources:
            - name: cpu
              weight: 1
            - name: memory
              weight: 1
            - name: nvidia.com/gpu
              weight: 3
            type: MostAllocated
        name: NodeResourcesFit
      schedulerName: binpack-scheduler
