# externalIP:
externalIP: 10.61.3.123
# Volume Settings
nfs:
  storageClassName: astrago-nfs-csi
  server: 10.61.3.123
  basePath: /astrago-volume
# GPU Process Exporter Settings
gpu-process-exporter:
  enabled: true
  collection:
    schedule: "*/1 * * * *" # Every minute
    image:
      repository: busybox
      tag: "1.35"
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 32Mi
  prometheus:
    serverService: prometheus-kube-prometheus-prometheus.prometheus.svc:9090
  gpu:
    count: 4
    devices: [0, 1, 2, 3]
  nodeSelector:
    nvidia.com/gpu.present: "true"
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
# Keycloak Settings
keycloak:
  adminUser: admin
  adminPassword: xiirocks
  servicePort: 30001
# Astrago Settings
astrago:
  proxyUrl:
  servicePort: 30080
  userInitPassword: astrago
  keycloak:
    externalKeycloakUrl:
    realm: astrago
    client: astrago-client
    clientSecret: astragosecret
    userInitPassword: astrago
  mariadb:
    rootPassword: root
    username: astrago
    password: xiirocks
    maxLifetime: "3595000"
  mongodb:
    url: mongodb://astrago:xiirocks@astrago-mongodb:27017/astrago?authSource=admin
  core:
    registry: "docker.io"
    repository: "xiilab/astrago-posco"
    imageTag: "core-stage-36379"
  batch:
    registry: "docker.io"
    repository: "xiilab/astrago-posco"
    imageTag: "batch-stage-36379"
  monitor:
    registry: "docker.io"
    repository: "xiilab/astrago-posco"
    imageTag: "monitor-stage-36379"
  frontend:
    registry: "docker.io"
    repository: "xiilab/astrago-posco"
    # registry: "10.61.3.161:30002"
    # repository: "astrago/frontend"
    imageTag: "frontend-stage-2e50"
  oneview:
    enabled: true
harbor:
  enabled: true
  servicePort: 30002
  adminPassword: Harbor12345
offline:
  registry: # 192.168.56.11:35000
  httpServer: # http://192.168.56.11
