apiVersion: v1
kind: Secret
metadata:
  name: {{ include "timescaledb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "timescaledb.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.auth.enableSuperuser }}
  postgres-password: {{ .Values.auth.superuserPassword | b64enc | quote }}
  {{- end }}
  username: {{ .Values.auth.username | b64enc | quote }}
  password: {{ .Values.auth.password | b64enc | quote }}
  database: {{ .Values.auth.database | b64enc | quote }} 