apiVersion: v1
kind: Service
metadata:
  name: {{ include "timescaledb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "timescaledb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "timescaledb.selectorLabels" . | nindent 4 }} 