apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodefeaturegroups.nfd.k8s-sigs.io
  labels:
    {{- include "custom-gpu-operator.labels" . | nindent 4 }}
    app.kubernetes.io/name: node-feature-discovery
spec:
  group: nfd.k8s-sigs.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              featureGroupRules:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    featureRules:
                      type: array
                      items:
                        type: object
                        properties:
                          feature:
                            type: string
                          matchLabels:
                            type: object
                            additionalProperties:
                              type: string
          status:
            type: object
  scope: Cluster
  names:
    plural: nodefeaturegroups
    singular: nodefeaturegroup
    kind: NodeFeatureGroup
    listKind: NodeFeatureGroupList 