keycloak:
  themeVersion: v1.1.5

# Chart Versions - 중앙 관리
chartVersions:
  csiDriverNfs: "v4.9.0"
  gpuOperator: "v24.9.0" 
  kubePrometheusStack: "61.9.0"
  flux2: "2.12.4"
  keycloak: "21.4.4"
  harbor: "1.14.2"
  mpiOperator: "1.2.2"

# GPU Process Exporter - Exports GPU process metrics to Prometheus
gpu-process-exporter:
  enabled: true

# Loki Stack - Complete logging solution with Loki and Promtail
loki:
  enabled: true
  retentionPeriod: "744h"  # 31 days
  replicas: 1
  resources:
    limits:
      cpu: "1000m"
      memory: "2Gi"
    requests:
      cpu: "500m"
      memory: "1Gi"
  persistence:
    enabled: true
    size: "10Gi"
    storageClass: "astrago-nfs-csi"

promtail:
  enabled: true
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
