keycloak:
  themeVersion: v1.1.5

# Chart Versions - 중앙 관리
chartVersions:
  csiDriverNfs: "v4.9.0"
  gpuOperator: "v24.9.0" 
  kubePrometheusStack: "61.9.0"
  flux2: "2.12.4"
  keycloak: "21.4.4"
  harbor: "1.14.2"
  mpiOperator: "1.2.2"

# GPU Process Exporter - Exports GPU process metrics to Prometheus
gpu-process-exporter:
  enabled: true
  collection:
    schedule: "*/1 * * * *" # Every minute
    image:
      repository: busybox
      tag: "1.35"
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 32Mi
  prometheus:
    serverService: prometheus-kube-prometheus-prometheus.prometheus.svc:9090
  gpu:
    count: 4
    devices: [0, 1, 2, 3]
  nodeSelector:
    nvidia.com/gpu.present: "true"
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule

# Loki Stack - Complete logging solution with Loki and Promtail
loki:
  replicas: 1
  resources:
    limits:
      cpu: "1000m"
      memory: "2Gi"
    requests:
      cpu: "500m"
      memory: "1Gi"
  persistence:
    enabled: true
    size: "20Gi"
    storageClass: "astrago-nfs-csi"
  retention:
    enabled: true
    period: "168h" # 7 days for dev environment
    compaction_interval: "10m"
    delete_delay: "2h"
    delete_worker_count: 150
  gpu:
    count: 4
    devices: [0, 1, 2, 3]
  nodeSelector:
    nvidia.com/gpu.present: "true"
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule

promtail:
  enabled: true
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
