repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
#- name: prometheus-volume
#  namespace: prometheus
#  chart: prometheus-volume
#  wait: true
#  labels:
#    app: prometheus
#  values:
#  - values.yaml.gotmpl

- name: prometheus
  namespace: prometheus
  # chart: prometheus-community/kube-prometheus-stack
  chart: kube-prometheus-stack
  wait: true
  labels:
    app: prometheus
  values:
  - values.yaml.gotmpl
