repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
- name: prometheus-volume
  namespace: prometheus
  chart: local-volume
  condition: local.enabled
  wait: true
  labels:
    app: prometheus
  values:
  - local-volume.yaml.gotmpl

- name: prometheus
  namespace: prometheus
  # chart: prometheus-community/kube-prometheus-stack
  chart: kube-prometheus-stack
  wait: true
  labels:
    app: prometheus
  values:
  - values.yaml.gotmpl
