repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus
    namespace: prometheus
    # chart: prometheus-community/kube-prometheus-stack
    chart: kube-prometheus-stack
    wait: true
    labels:
      app: prometheus
      type: infra
    values:
    - kube-prometheus-stack/custom_values.yaml
