# Default values for uyuni.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
core:
  image:
    repository: xiilab/astrago
    tag: core-v1.0.7
  serviceAccount:
    name: "astrago-sa"
  service:
    type: NodePort
    port: 8080
    nodePort: 30081
      
batch:
  image:
    repository: xiilab/astrago
    tag: batch-v1.0.7
  serviceAccount:
    name: "astrago-sa"      
  service:
    type: NodePort
    port: 8080
    nodePort: 30082

monitor:
  image:
    repository: xiilab/astrago
    tag: monitor-v1.0.7
  serviceAccount:
    name: "astrago-sa"      
  service:
    type: NodePort
    port: 8080
    nodePort: 30083

frontend:
  image:
    repository: xiilab/astrago
    tag: v1.0.8
  service:
    type: NodePort
    port: 3000
