# Default values for uyuni.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
core:
  image:
    repository: xiilab/uyuni-backend-core
    tag: master
  serviceAccount:
    name: "astrago-sa"
  service:
    type: NodePort
    port: 8080
    nodePort: 30081
batch:
  image:
    repository: xiilab/uyuni-backend-batch
    tag: master
  serviceAccount:
    name: "astrago-sa"
  service:
    type: NodePort
    port: 8080
    nodePort: 30082
monitor:
  image:
    repository: xiilab/uyuni-backend-monitor
    tag: master
  serviceAccount:
    name: "astrago-sa"
  service:
    type: NodePort
    port: 8080
    nodePort: 30083
frontend:
  image:
    repository: xiilab/astrago
    tag: frontend-v1.0.9
  service:
    type: NodePort
    port: 3000
