# Default values for uyuni.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
core:
  replicaCount: 3
  image:
    repository: xiilab/uyuni-backend-core
    tag: master
  serviceAccount:
    name: "astrago-sa"
  service:
    type: NodePort
    port: 8080
    nodePort: 30081
      
batch:
  image:
    repository: xiilab/uyuni-backend-batch
    tag: master
  serviceAccount:
    name: "astrago-sa"      
  service:
    type: NodePort
    port: 8080
    nodePort: 30082

monitor:
  image:
    repository: xiilab/uyuni-backend-monitor
    tag: master
  serviceAccount:
    name: "astrago-sa"      
  service:
    type: NodePort
    port: 8080
    nodePort: 30083

frontend:
  image:
    repository: xiilab/uyuni-frontend
    tag: master
  service:
    type: NodePort
    port: 3000
    nodePort: 30080      

