apiVersion: apps/v1
kind: Deployment
metadata:
  name: astrago-backend-core
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: astrago-backend-core
spec:
  {{- if not .Values.core.autoscaling.enabled }}
  replicas: {{ .Values.core.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: astrago-backend-core
  template:
    metadata:
      {{- with .Values.core.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: astrago-backend-core
    spec:
      {{- with .Values.core.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "common.serviceAccountName" . }}      
      securityContext:
        {{- toYaml .Values.core.podSecurityContext | nindent 8 }}
      {{- if .Values.astrago.truststore.enabled }}
      initContainers:
        - name: setup-truststore
          image: "{{ default .Values.core.image.registry .Values.global.imageRegistry }}/{{ .Values.core.image.repository }}:{{ .Values.core.image.tag }}"
          command: ["/bin/bash"]
          args:
            - -c
            - |
              echo "Setting up truststore with TLS certificate..."
              cp $JAVA_HOME/lib/security/cacerts /opt/truststore/cacerts
              echo "Importing TLS certificate: astrago-cert"
              keytool -import -alias astrago-cert -file /tmp/certs/tls.crt -keystore /opt/truststore/cacerts -storepass changeit -noprompt
              echo "TLS certificate imported successfully"
          volumeMounts:
            - name: truststore
              mountPath: /opt/truststore
            - name: {{ .Values.astrago.tls.secretName | default "astrago-tls-secret" }}
              mountPath: /tmp/certs
      {{- else }}
      {{- with .Values.core.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.core.securityContext | nindent 12 }}          
          image: "{{ default .Values.core.image.registry .Values.global.imageRegistry }}/{{ .Values.core.image.repository }}:{{ .Values.core.image.tag }}"
          imagePullPolicy: {{ .Values.core.image.pullPolicy }}      
          command: ["java"]
          args:
          - "-Duser.timezone=Asia/Seoul"
          {{- if .Values.astrago.truststore.enabled }}
          - "-Djavax.net.ssl.trustStore=/opt/truststore/cacerts"
          - "-Djavax.net.ssl.trustStorePassword=changeit"
          {{- else }}
          - "-Djavax.net.ssl.trustStore=/root/astrago/cacerts"
          - "-Djavax.net.ssl.trustStorePassword=changeit"
          {{- end }}
          - "-jar"
          - "/java/app.jar"
          env:
          {{- range $key, $obj := .Values.core.env }}
          - name: {{ $obj.name }}
            value: {{ $obj.value | quote }}
          {{- end }}
          volumeMounts:
            - name: astrago-workload-log
              mountPath: /root/astrago
            {{- if .Values.astrago.truststore.enabled }}
            - name: truststore
              mountPath: /opt/truststore
            {{- end }}
            {{- with .Values.core.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.core.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.core.resources | nindent 12 }}
      volumes:
        - name: astrago-workload-log
          persistentVolumeClaim:
            claimName: workload-log-pvc
        {{- if .Values.astrago.truststore.enabled }}
        - name: truststore
          emptyDir: {}
        - name: {{ .Values.astrago.tls.secretName | default "astrago-tls-secret" }}
          secret:
            secretName: {{ .Values.astrago.tls.secretName | default "astrago-tls-secret" }}
        {{- end }}
        {{- with .Values.core.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.core.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.core.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.core.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10