auth:
  adminUser: admin
  adminPassword: "xiirocks"
service:
  type: NodePort
  nodePorts:
    http: "30001"
    https: "30002"

postgresql:
  primary:
    persistence:
      enabled: true
      existingClaim: "keycloak-volume"

createVolume:
  enabled: true
  name: keycloak-volume
  size: 8Gi
  accessModes:
    - ReadWriteOnce     
  volumeType: nfs
  nfs:
    server: 10.61.3.2
    path: /kube_storage/staging-astrago-keycloak-volume

