auth:
  adminUser: admin
  adminPassword: "xiirocks"

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: 10.61.3.33.nip.io
  path: /auth
  pathType: Prefix
  servicePort: http
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
service:
  type: NodePort
  nodePorts:
    http: "30001"
    https: "30002"

extraVolumes:
  - name: theme
    emptyDir: {}
## @param extraVolumeMounts Optionally specify extra list of additional volumeMounts for Keycloak container(s)
##
extraVolumeMounts:
  - name: theme
    mountPath: /opt/bitnami/keycloak/providers/keycloak-theme.jar
    subPath: keycloak-theme.jar

## @param initContainers Add additional init containers to the Keycloak pods
## Example:
## initContainers:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##     ports:
##       - name: portname
##         containerPort: 1234
##
initContainers:
  - name: download-astra-logintheme
    image: jacobcarlborg/docker-alpine-wget
    command:
      - sh
    args:
      - -c
      - |
       echo "check_certificate = off" >> ~/.wgetrc && wget https://github.com/xiilab/uyuni-login-theme/releases/download/v1.0.13/keycloak-theme.jar -P /theme

    volumeMounts:
      - name: theme
        mountPath: /theme

postgresql:
  primary:
    persistence:
      enabled: true
      existingClaim: "keycloak-volume"

createVolume:
  enabled: true
  name: keycloak-volume
  size: 8Gi
  accessModes:
    - ReadWriteOnce     
  volumeType: nfs
  nfs:
    server: 10.61.3.2
    path: /kube_storage/staging-astrago-keycloak-volume

