# Customer-specific overrides for xiilab environment
# These values override the base configuration

# Customer-specific network settings
nfs:
  server: 10.61.3.2 # xiilab NFS 서버
# Keycloak Settings - base에서 기본 활성화됨

# Astrago Settings - xiilab 전용 설정
astrago:
  baseUrl: https://demo.astrago.ai # xiilab 도메인 (TLS 사용)
  global:
    imagePullSecrets:
      - name: ghcr-secret # GHCR 프라이빗 레지스트리 접근
  # xiilab 전용 이미지 태그 (GHCR)
  core:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
    imageTag: "core-stage-1.0-d7f80d8a"
  batch:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
    imageTag: "batch-stage-1.0-d7f80d8a"
  monitor:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
    imageTag: "monitor-stage-1.0-d7f80d8a"
  frontend:
    registry: "ghcr.io"
    repository: "xiilab/astrago-frontend"
    imageTag: "frontend-stage-1.0-bdca8512"
# Astrago Ingress Settings - xiilab 전용 도메인
ingress:
  host: demo.astrago.ai # xiilab 전용 도메인
  tls:
    enabled: false  # 외부 nginx에서 TLS 처리
    secretName: "astrago-tls-cert"  # Backend cacerts용 인증서는 필요
  additionalAnnotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"  # Backend cacerts용 인증서 생성
    # 외부 nginx에서 TLS 터미네이션하므로 내부는 HTTP 처리
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # HTTP 허용
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"  # HTTPS 강제 해제
# Keycloak Settings - xiilab 전용 도메인
keycloak:
  ingress:
    host: "demo.astrago.ai"  # xiilab 도메인 (Astrago와 동일)
  image:
    tag: "v1.2.0"
# LoadBalancer IP - xiilab 인프라
ingressNginx:
  loadBalancerIP: "10.61.3.163" # xiilab LoadBalancer IP
