# Customer-specific overrides for Astrago customer
# These values override the base configuration

# Customer-specific network settings
externalIP: 10.61.3.161
nfs:
  server: 10.61.3.2
  basePath: /kube_storage

astrago:
  core:
    repository: "xiilab/astrago-posco"
    imageTag: "core-stage-ba01"
  batch:
    repository: "xiilab/astrago-posco"
    imageTag: "batch-stage-ba01"
  monitor:
    repository: "xiilab/astrago-posco"
    imageTag: "monitor-stage-ba01"
  frontend:
    repository: "xiilab/astrago-posco"
    imageTag: "frontend-stage-2e50"