# Customer-specific overrides for xiilab environment
# These values override the base configuration

# Customer-specific network settings
nfs:
  server: 10.61.3.2  # xiilab NFS 서버

# Keycloak Settings - xiilab 환경에서 Ingress 활성화
keycloak:
  ingress:
    enabled: true  # xiilab 환경에서 Keycloak Ingress 활성화

# Astrago Settings - xiilab 전용 설정
astrago:
  baseUrl: http://demo.astrago.ai  # xiilab 도메인
  global:
    imagePullSecrets:
      - name: ghcr-secret  # GHCR 프라이빗 레지스트리 접근

  # xiilab 전용 이미지 태그 (GHCR)
  core:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
    imageTag: "core-stage-1.0-00e50ff5"
  batch:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
    imageTag: "batch-stage-1.0-00e50ff5"
  monitor:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
    imageTag: "monitor-stage-1.0-00e50ff5"
  frontend:
    registry: "ghcr.io"
    repository: "xiilab/astrago-frontend"
    imageTag: "frontend-stage-1.0-bdca8512"

# Astrago Ingress Settings - xiilab 활성화
ingress:
  enabled: true  # xiilab 환경에서 Ingress 활성화
  host: demo.astrago.ai  # xiilab 전용 도메인

# LoadBalancer IP - xiilab 인프라
ingressNginx:
  loadBalancerIP: "10.61.3.163"  # xiilab LoadBalancer IP
