# Customer-specific overrides for xiilab environment
# These values override the base configuration

# External Access Configuration
externalAccess:
  mode: "domain"  # Using domain-based access with TLS
  ip:
    address: "10.61.3.163"  # LoadBalancer IP (same as ingressNginx.loadBalancerIP)
  domain:
    name: "demo.astrago.ai"
    tls:
      enabled: true
      issuer: "letsencrypt-prod"
      secretName: "astrago-tls-cert"

# Customer-specific network settings
nfs:
  server: 10.61.3.2 # xiilab NFS 서버

# Astrago Settings - xiilab 전용 설정
astrago:
  baseUrl: https://demo.astrago.ai  # 외부 접근 URL
  global:
    imagePullSecrets:
      - name: ghcr-secret # GHCR 프라이빗 레지스트리 접근
  # xiilab 전용 이미지 설정 (GHCR)
  imageDefaults:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
  components:
    core:
      tag: "core-stage-1.0-23c6b0c4"
    batch:
      tag: "batch-stage-1.0-23c6b0c4"
    monitor:
      tag: "monitor-stage-1.0-23c6b0c4"
    frontend:
      repository: "xiilab/astrago-frontend"  # frontend만 다른 repository 사용
      tag: "frontend-stage-1.0-de783097"

# Ingress annotations (도메인 모드이지만 외부 nginx에서 TLS 처리하므로 k8s 리다이렉트 비활성화)
ingress:
  additionalAnnotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"

# Keycloak Settings
keycloak:
  image:
    tag: "v0.1.2_test"

# LoadBalancer IP - xiilab 인프라
ingressNginx:
  loadBalancerIP: "10.61.3.163" # xiilab LoadBalancer IP
