# Customer-specific overrides for Astrago customer
# These values override the base configuration

# Customer-specific network settings
nfs:
  server: 10.61.3.2
  basePath: /kube_storage

# Keycloak Settings (customer-specific image)
keycloak:
  image:
    registry: "ghcr.io"
    repository: "xiilab/keycloak-astrago"
    tag: "22.0.5-theme-latest"
astrago:
  baseUrl: http://demo.astrago.ai
  global:
    imagePullSecrets:
      - name: ghcr-secret
  core:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
    imageTag: "core-stage-1.0-00e50ff5"
  batch:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
    imageTag: "batch-stage-1.0-00e50ff5"
  monitor:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
    imageTag: "monitor-stage-1.0-00e50ff5"
  frontend:
    registry: "ghcr.io"
    repository: "xiilab/astrago-frontend"
    imageTag: "frontend-stage-1.0-bdca8512"

# Ingress NGINX LoadBalancer IP for xiilab environment
ingressNginx:
  loadBalancerIP: "10.61.3.163"
