# Customer-specific overrides for Astrago customer
# These values override the base configuration

# Customer-specific network settings
externalIP: 10.61.3.161
nfs:
  server: 10.61.3.2
  basePath: /kube_storage
astrago:
  global:
    imagePullSecrets:
      - name: ghcr-secret
  core:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
    imageTag: "core-stage-1.0-bd279cbf"
  batch:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
    imageTag: "batch-stage-1.0-bd279cbf"
  monitor:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
    imageTag: "monitor-stage-1.0-bd279cbf"
  frontend:
    registry: "ghcr.io"
    repository: "xiilab/astrago-frontend"
    imageTag: "frontend-stage-1.0-489003b2"
