# Customer-specific overrides for xiilab environment
# These values override the base configuration

# Customer-specific network settings
nfs:
  server: 10.61.3.2 # xiilab NFS 서버
# Keycloak Settings - base에서 기본 활성화됨

# Astrago Settings - xiilab 전용 설정
astrago:
  baseUrl: https://demo.astrago.ai # xiilab 도메인 (TLS 사용)
  global:
    imagePullSecrets:
      - name: ghcr-secret # GHCR 프라이빗 레지스트리 접근
  # xiilab 전용 이미지 태그 (GHCR)
  core:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
    imageTag: "core-stage-1.0-d9d0323a"
  batch:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
    imageTag: "batch-stage-1.0-d9d0323a"
  monitor:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
    imageTag: "monitor-stage-1.0-d9d0323a"
  frontend:
    registry: "ghcr.io"
    repository: "xiilab/astrago-frontend"
    imageTag: "frontend-stage-1.0-de783097"
# Astrago Ingress Settings - xiilab 전용 도메인
ingress:
  host: demo.astrago.ai # xiilab 전용 도메인
  tls:
    enabled: true # K8s ingress에서 TLS 처리
    secretName: "astrago-tls-cert"
  additionalAnnotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Let's Encrypt 실제 인증서 자동 발급
    nginx.ingress.kubernetes.io/ssl-redirect: "false" # 외부 nginx에서 처리하므로 비활성화
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false" # 외부 nginx에서 처리하므로 비활성화
# Keycloak Settings - xiilab 전용 도메인
keycloak:
  ingress:
    host: "demo.astrago.ai" # xiilab 도메인 (Astrago와 동일)
    # TLS는 Astrago ingress에서 처리되므로 별도 설정 불필요
  image:
    tag: "v0.1.2_test"
# LoadBalancer IP - xiilab 인프라
ingressNginx:
  loadBalancerIP: "10.61.3.163" # xiilab LoadBalancer IP
