# Customer-specific overrides for xiilab environment
# These values override the base configuration

# External Access Configuration
externalAccess:
  mode: "domain"  # Using domain-based access with TLS
  ip:
    address: "10.61.3.163"  # LoadBalancer IP (ingress-nginx controller)
  domain:
    name: "demo.astrago.ai"
    tls:
      enabled: true
      issuer: "letsencrypt-prod"  # cert-manager가 인증서 자동 생성
      secretName: "astrago-tls-cert"

# Customer-specific network settings
nfs:
  server: 10.61.3.2 # xiilab NFS 서버

# Astrago Settings - xiilab 전용 설정
astrago:
  baseUrl: https://demo.astrago.ai  # 외부 접근 URL
  global:
    imagePullSecrets:
      - name: ghcr-secret # GHCR 프라이빗 레지스트리 접근
  # xiilab 전용 이미지 설정 (GHCR)
  imageDefaults:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
  components:
    core:
      tag: "core-stage-1.0-23c6b0c4"
    batch:
      tag: "batch-stage-1.0-23c6b0c4"
    monitor:
      tag: "monitor-stage-1.0-23c6b0c4"
    frontend:
      tag: "frontend-stage-1.0-de783097"

# Keycloak Settings
keycloak:
  image:
    tag: "v0.1.2_test"
