# Customer-specific overrides for Astrago customer
# These values override the base configuration

# Customer-specific network settings
externalIP: 10.61.3.161
nfs:
  server: 10.61.3.2
  basePath: /kube_storage
astrago:
  core:
    repository: "ghcr.io/xiilab/astrago-backend"
    imageTag: "core-stage-ca58a8c3"
  batch:
    repository: "ghcr.io/xiilab/astrago-backend"
    imageTag: "batch-stage-ca58a8c3"
  monitor:
    repository: "ghcr.io/xiilab/astrago-backend"
    imageTag: "monitor-stage-ca58a8c3"
  frontend:
    repository: "xiilab/astrago-posco"
    imageTag: "frontend-stage-2e50"
