# Customer-specific overrides for Astrago customer
# These values override the base configuration

# Customer-specific network settings
externalIP: 10.61.3.161
nfs:
  server: 10.61.3.2
  basePath: /kube_storage
astrago:
  core:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
    imageTag: "core-stage-ca58a8c3"
    imagePullSecrets:
      - name: ghcr-secret
  batch:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
    imageTag: "batch-stage-ca58a8c3"
    imagePullSecrets:
      - name: ghcr-secret
  monitor:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
    imageTag: "monitor-stage-ca58a8c3"
    imagePullSecrets:
      - name: ghcr-secret
  frontend:
    repository: "xiilab/astrago-posco"
    imageTag: "frontend-stage-2e50"
