apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "loki-stack.fullname" . }}-promtail
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki-stack.labels" . | nindent 4 }}
    app: promtail
    component: promtail
spec:
  selector:
    matchLabels:
      app: promtail
      component: promtail
  template:
    metadata:
      labels:
        app: promtail
        component: promtail
    spec:
      serviceAccountName: {{ include "loki-stack.fullname" . }}-promtail
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: promtail
        image: {{ .Values.promtail.image.repository }}:{{ .Values.promtail.image.tag }}
        imagePullPolicy: {{ .Values.promtail.image.pullPolicy | default "IfNotPresent" }}
        securityContext:
          privileged: true
          runAsUser: 0
          runAsGroup: 0
        args:
          - -config.file=/etc/promtail/config.yaml
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: config
          mountPath: /etc/promtail
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: run
          mountPath: /run/promtail
        resources:
          {{- toYaml .Values.promtail.resources | nindent 10 }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      volumes:
      - name: config
        configMap:
          name: {{ include "loki-stack.fullname" . }}-promtail-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: run
        hostPath:
          path: /run/promtail 