---
# Source: uyuni/charts/mariadb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: uyuni-mariadb
  namespace: "uyuni"
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-12.2.9
    app.kubernetes.io/instance: uyuni
    app.kubernetes.io/managed-by: Helm
  annotations:
automountServiceAccountToken: false
---
# Source: uyuni/charts/mariadb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: uyuni-mariadb
  namespace: "uyuni"
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-12.2.9
    app.kubernetes.io/instance: uyuni
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  mariadb-root-password: "eEQyMk9KWlp2SQ=="
---
# Source: uyuni/charts/mariadb/templates/primary/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: uyuni-mariadb
  namespace: "uyuni"
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-12.2.9
    app.kubernetes.io/instance: uyuni
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
data:
  my.cnf: |-
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    datadir=/bitnami/mariadb/data
    plugin_dir=/opt/bitnami/mariadb/plugin
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    slow_query_log=0
    long_query_time=10.0
    
    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mariadb/plugin
    
    [manager]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
---
# Source: uyuni/charts/batch/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: uyuni-backend-batch
  namespace: uyuni
  labels:
    helm.sh/chart: batch-0.1.1
    app.kubernetes.io/name: batch
    app.kubernetes.io/instance: uyuni
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: batch
    app.kubernetes.io/instance: uyuni
---
# Source: uyuni/charts/core/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: uyuni-backend-core
  namespace: uyuni
  labels:
    helm.sh/chart: core-0.1.1
    app.kubernetes.io/name: core
    app.kubernetes.io/instance: uyuni
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: core
    app.kubernetes.io/instance: uyuni
---
# Source: uyuni/charts/frontend/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: uyuni-frontend
  namespace: uyuni
  labels:
    helm.sh/chart: frontend-0.1.0
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: uyuni
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: uyuni
---
# Source: uyuni/charts/mariadb/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: uyuni-mariadb
  namespace: "uyuni"
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-12.2.9
    app.kubernetes.io/instance: uyuni
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
  annotations:
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: mysql
      nodePort: null
  selector: 
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: uyuni
    app.kubernetes.io/component: primary
---
# Source: uyuni/charts/monitor/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: uyuni-backend-monitor
  namespace: uyuni
  labels:
    helm.sh/chart: monitor-0.1.1
    app.kubernetes.io/name: monitor
    app.kubernetes.io/instance: uyuni
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: monitor
    app.kubernetes.io/instance: uyuni
---
# Source: uyuni/charts/batch/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uyuni-backend-batch
  namespace: uyuni
  labels:
    helm.sh/chart: batch-0.1.1
    app.kubernetes.io/name: batch
    app.kubernetes.io/instance: uyuni
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: batch
      app.kubernetes.io/instance: uyuni
  template:
    metadata:
      labels:
        app.kubernetes.io/name: batch
        app.kubernetes.io/instance: uyuni
    spec:
      securityContext:
        {}
      containers:
        - name: batch
          securityContext:
            {}
          image: "xiilab/uyuni-backend-batch:1.16.0"
          imagePullPolicy: IfNotPresent

          env:
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {}
---
# Source: uyuni/charts/core/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uyuni-backend-core
  namespace: uyuni
  labels:
    helm.sh/chart: core-0.1.1
    app.kubernetes.io/name: core
    app.kubernetes.io/instance: uyuni
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: core
      app.kubernetes.io/instance: uyuni
  template:
    metadata:
      labels:
        app.kubernetes.io/name: core
        app.kubernetes.io/instance: uyuni
    spec:
      securityContext:
        {}
      containers:
        - name: core
          securityContext:
            {}
          image: "xiilab/uyuni-backend-core:1.16.0"
          imagePullPolicy: IfNotPresent
          
          env:

          
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          resources:
            {}
---
# Source: uyuni/charts/frontend/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uyuni-frontend
  namespace: uyuni
  labels:
    helm.sh/chart: frontend-0.1.0
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: uyuni
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/instance: uyuni
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/instance: uyuni
    spec:
      securityContext:
        {}
      containers:
        - name: frontend
          securityContext:
            {}
          image: ":"
          imagePullPolicy: Always
          
          env:
          - name: KEYCLOAK_HOST
            value: "https://auth.bigdata-car.kr"
          - name: KEYCLOAK_REALME
            value: "test"
          - name: KEYCLOAK_CLIENT_ID
            value: "test"
          - name: AUTH_CLIENT_ID
            value: "test"
          - name: AUTH_CLIENT_SECRET
            value: "MEWDnE6z8WG2J54kdGGq5o9jI7S4PQev"
          - name: AUTH_ISSUER
            value: "https://auth.bigdata-car.kr/realms/test"
          - name: NEXTAUTH_URL
            value: "http://marketplace.xiilab.com/"
          - name: NEXTAUTH_SECRET
            value: "4ohzMZuO6li816GRSIl6qvESluvGSBayA42z6kVSaWE="
          - name: NEXT_PUBLIC_API_URL
            value: "http://marketplace.xiilab.com/"
          
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
# Source: uyuni/charts/monitor/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uyuni-backend-monitor
  namespace: uyuni
  labels:
    helm.sh/chart: monitor-0.1.1
    app.kubernetes.io/name: monitor
    app.kubernetes.io/instance: uyuni
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: monitor
      app.kubernetes.io/instance: uyuni
  template:
    metadata:
      labels:
        app.kubernetes.io/name: monitor
        app.kubernetes.io/instance: uyuni
    spec:
      securityContext:
        {}
      containers:
        - name: monitor
          securityContext:
            {}
          image: "xiilab/uyuni-backend-monitor:1.16.0"
          imagePullPolicy: IfNotPresent
          env:
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {}
---
# Source: uyuni/charts/mariadb/templates/primary/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uyuni-mariadb
  namespace: "uyuni"
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-12.2.9
    app.kubernetes.io/instance: uyuni
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels: 
      app.kubernetes.io/name: mariadb
      app.kubernetes.io/instance: uyuni
      app.kubernetes.io/component: primary
  serviceName: uyuni-mariadb
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/configuration: a02ed98369ad65c29976e09e7b98bb087002117fff61c1b02d5b699eca359860
      labels:
        app.kubernetes.io/name: mariadb
        helm.sh/chart: mariadb-12.2.9
        app.kubernetes.io/instance: uyuni
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: primary
    spec:
      
      serviceAccountName: uyuni-mariadb
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: mariadb
                    app.kubernetes.io/instance: uyuni
                    app.kubernetes.io/component: primary
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
      containers:
        - name: mariadb
          image: docker.io/bitnami/mariadb:10.11.4-debian-11-r46
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            runAsUser: 1001
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uyuni-mariadb
                  key: mariadb-root-password
            - name: MARIADB_DATABASE
              value: "my_database"
          ports:
            - name: mysql
              containerPort: 3306
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  password_aux="${MARIADB_ROOT_PASSWORD:-}"
                  if [[ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]]; then
                      password_aux=$(cat "$MARIADB_ROOT_PASSWORD_FILE")
                  fi
                  mysqladmin status -uroot -p"${password_aux}"
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  password_aux="${MARIADB_ROOT_PASSWORD:-}"
                  if [[ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]]; then
                      password_aux=$(cat "$MARIADB_ROOT_PASSWORD_FILE")
                  fi
                  mysqladmin status -uroot -p"${password_aux}"
          resources: 
            limits: {}
            requests: {}
          volumeMounts:
            - name: data
              mountPath: /bitnami/mariadb
            - name: config
              mountPath: /opt/bitnami/mariadb/conf/my.cnf
              subPath: my.cnf
      volumes:
        - name: config
          configMap:
            name: uyuni-mariadb
  volumeClaimTemplates:
    - metadata:
        name: data
        labels: 
          app.kubernetes.io/name: mariadb
          app.kubernetes.io/instance: uyuni
          app.kubernetes.io/component: primary
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"

