{{- if index .Values "gpu-process-exporter" "enabled" }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gpu-process-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: gpu-process-exporter
    chart: {{ include "gpu-process-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: gpu-process-exporter
  template:
    metadata:
      labels:
        app: gpu-process-exporter
        release: {{ .Release.Name }}
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      hostPID: true
      containers:
      - name: gpu-process-exporter
        image: "xiilab/gpu-process-exporter:v2.1-go"
        ports:
        - name: metrics
          containerPort: {{ .Values.httpServer.port }}
          protocol: TCP
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: METRICS_PORT
          value: {{ .Values.httpServer.port | quote }}
        securityContext:
          privileged: true
        resources:
          {{- toYaml .Values.httpServer.resources | nindent 10 }}
        volumeMounts:
        - name: host-proc
          mountPath: /host/proc
          readOnly: true
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.httpServer.port }}
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.httpServer.port }}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
      volumes:
      - name: host-proc
        hostPath:
          path: /proc

{{- if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: gpu-process-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: gpu-process-exporter
    chart: {{ include "gpu-process-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: metrics
  selector:
    app: gpu-process-exporter
{{- end }}

{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gpu-process-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: gpu-process-exporter
    chart: {{ include "gpu-process-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- toYaml .Values.serviceMonitor.selector | nindent 4 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    path: /metrics
{{- end }}
{{- end }}
