apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: astrago-mongodb
  namespace: {{ .Release.Namespace }}
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: admin-scram
    - name: astrago
      db: admin
      passwordSecretRef:
        name: astrago-password
      roles:
        - name: readWrite
          db: astrago
      scramCredentialsSecretName: astrago-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: astrago-nfs-csi
            resources:
              requests:
                storage: 10Gi
        - metadata:
            name: logs-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: astrago-nfs-csi
            resources:
              requests:
                storage: 5Gi
      template:
        spec:
          containers:
            - name: mongod
              resources:
                requests:
                  cpu: "500m"
                  memory: "2Gi"
                limits:
                  cpu: "1"
                  memory: "4Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: external-mongo-service-0
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: astrago-mongodb-svc
    statefulset.kubernetes.io/pod-name: astrago-mongodb-0
  ports:
    - protocol: TCP
      nodePort: 30011
      port: 30011
      targetPort: 27017
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-password
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: eGlpcm9ja3M=
---
apiVersion: v1
kind: Secret
metadata:
  name: astrago-password
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: eGlpcm9ja3M=
