kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: binpack-scheduler
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: binpack-scheduler
subjects:
- kind: ServiceAccount
  name: binpack-scheduler
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: binpack-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: binpack-scheduler-as-kube-scheduler
subjects:
- kind: ServiceAccount
  name: binpack-scheduler
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: binpack-scheduler-as-volume-scheduler
subjects:
- kind: ServiceAccount
  name: binpack-scheduler
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
