apiVersion: v2
name: redis
description: A Helm chart for Redis
version: 0.1.0
appVersion: "7.2"

keywords:
  - redis
  - cache
  - database
  - memory

home: https://redis.io/
sources:
  - https://github.com/redis/redis

maintainers:
  - name: AstraGo Team
    email: devops@astrago.com

type: application 