{{- if .Values.astrago.ingress.enabled -}}
{{- $fullName := include "common.fullname" . -}}
{{- $svcPort := .Values.proxy.service.port | default 80 -}}
{{- $annotations := dict -}}
{{- if .Values.astrago.ingress.annotations }}
  {{- $annotations = .Values.astrago.ingress.annotations }}
{{- end }}
{{- if and .Values.astrago.ingress.className (not (hasKey $annotations "kubernetes.io/ingress.class")) }}
  {{- $_ := set $annotations "kubernetes.io/ingress.class" .Values.astrago.ingress.className}}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- if gt (len $annotations) 0 }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.astrago.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.astrago.ingress.className }}
  {{- end }}
  {{- if or .Values.ingress.tls .Values.astrago.ingress.tls.enabled }}
  tls:
    {{- if .Values.astrago.ingress.tls.enabled }}
    {{/* ASTRAGO TLS 설정 (Manual Secret 방식) */}}
    - secretName: {{ .Values.astrago.tls.secretName | default "astrago-tls-secret" }}
      hosts:
        - {{ .Values.astrago.ingress.host | quote }}
    {{- else if .Values.ingress.tls }}
    {{/* 기존 방식 (하위 호환성) */}}
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.astrago.ingress.host | quote }}
      http:
        paths:
          - path: /
            {{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
              service:
                name: nginx-service
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: nginx-service
              servicePort: {{ $svcPort }}
              {{- end }}
{{- end }}