apiVersion: apps/v1
kind: Deployment
metadata:
  name: astrago-time-prediction
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astrago-time-prediction
  template:
    metadata:
      labels:
        app: astrago-time-prediction
    spec:
      containers:
      - name: astrago-time-prediction
        image: xiilab/astrago:time-prediction  # 이미지 이름 수정
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: astrago-time-prediction
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: astrago-time-prediction
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
