apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workload-log-pvc
  namespace: {{ .Release.Namespace | quote }}
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  accessModes:
    {{- range .Values.persistence.accessMode }}
    - {{ . | quote }}
    {{- end }}
  storageClassName: {{ .Values.persistence.storageClass }}
