# externalIP: 
externalIP:
# Volume Settings
nfs:
  enabled: false
  storageClassName: astrago-nfs-csi
  server:
  basePath:
local:
  enabled: false
  storageClassName: astrago-local-storage
  nodeName:
  basePath:
# Keycloak Settings
keycloak:
  themeVersion: v1.1.3
  adminUser: admin
  adminPassword: xiirocks
  servicePort: 30001
# Astrago Settings
astrago:
  servicePort: 30080
  userInitPassword: astrago
  keycloak:
    realm: astrago
    client: astrago-client
    clientSecret: astragosecret
    userInitPassword: astrago
  mariadb:
    rootPassword: root
    username: astrago
    password: xiirocks
    maxLifetime: "3595000"
  core:
    repository: "xiilab/astrago"
    imageTag: "v1.0.2"
  batch:
    repository: "xiilab/astrago"
    imageTag: "v1.0.2"
  monitor:
    repository: "xiilab/astrago"
    imageTag: "v1.0.2"
  frontend:
    repository: "xiilab/astrago"
    imageTag: v1.0.1
