externalIP: 10.61.3.83 #변경필요 
ingress:
  enabled: false  # NodePort 모드 기본값 (--mode=ingress로 변경 가능)

gpu_operator:
  driver:
    version: "570.172.08" # 설치된 NVIDIA GPU Driver Version
  fabricManager:
    version: "570.172.08" # Fabric Manager Version == NVIDIA GPU Driver Version 
    enabled: true # Enable fabric manager
# Volume Settings
nfs:
  storageClassName: astrago-nfs-csi
  server: 10.61.3.83 #변경필요 
  basePath: /nfs-data/astrago
# Keycloak Settings
keycloak:
  adminUser: admin
  adminPassword: xiirocks
  servicePort: 30001
  serviceType: #ClusterIP  # ClusterIP OR NodePort
  image:
    repository: xiilab/astrago-keycloak-theme
    tag: "v1.2.0" # common/values.yaml의 themeVersion과 동기화
    pullPolicy: Always
# Astrago Settings
astrago:
  proxyUrl: #https://10.61.3.83.nip.io
  servicePort: 30080
  userInitPassword: astrago
  global:
    imagePullSecrets:
      - name: ghcr-pull-secret # GHCR 프라이빗 레지스트리 접근

  # === TLS SSL SET ===
  tls:
    secretName: "astrago-tls-secret"  # USED TLS Secret NAME
  
  # === Ingress SETTING (Secret create) ===
  ingress:
    enabled: false  # NodePort 모드 기본값 (--mode=ingress로 변경 가능)
    className: "nginx"
    host: #"10.61.3.83.nip.io"  # externalIP와 일치하도록 수정
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      # limit size (proxy-config.yaml의 client_max_body_size 0)
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      # proxy buffer size (proxy-config.yaml)
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
      nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
      nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "256k"  # ← proxy-buffer-size보다 크거나 같아야함.
      # Timeout set (proxy-config.yaml)
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
      # large header size
      nginx.ingress.kubernetes.io/large-client-header-buffers: "8 8k"
    tls:
      enabled: false  # Ingress 모드일 때만 필요 (NodePort 기본값: false)
  
  # === Truststore set (Secret) ===  
  truststore:
    enabled: false  # Ingress 모드일 때만 필요 (NodePort 기본값: false)

  keycloak:
    externalKeycloakUrl:
    realm: astrago
    client: astrago-client
    clientSecret: astragosecret
    userInitPassword: astrago
  mariadb:
    rootPassword: root
    username: astrago
    password: xiirocks
    maxLifetime: "1800000"
  core:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
    imageTag: "core-stage-1.0-0f278276"
  batch:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
    imageTag: "batch-stage-1.0-0f278276"
  monitor:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
    imageTag: "monitor-stage-1.0-0f278276"
  frontend:
    registry: "ghcr.io"
    repository: "xiilab/astrago-frontend"
    imageTag: "frontend-stage-1.0-9c31f980"
  oneview:
    enabled: false

harbor:
  servicePort: 30002
  enabled: true
  adminPassword: Harbor12345
offline:
  registry: # 192.168.56.11:35000
  httpServer: # http://192.168.56.11
