apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki-stack.fullname" . }}-loki
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki-stack.labels" . | nindent 4 }}
    app: loki
    component: loki
spec:
  type: ClusterIP
  ports:
  - port: 3100
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: loki
    component: loki 