apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "loki-stack.fullname" . }}-promtail
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki-stack.labels" . | nindent 4 }}
    app: promtail
    component: promtail
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "loki-stack.fullname" . }}-promtail
  labels:
    {{- include "loki-stack.labels" . | nindent 4 }}
    app: promtail
    component: promtail
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "loki-stack.fullname" . }}-promtail
  labels:
    {{- include "loki-stack.labels" . | nindent 4 }}
    app: promtail
    component: promtail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "loki-stack.fullname" . }}-promtail
subjects:
- kind: ServiceAccount
  name: {{ include "loki-stack.fullname" . }}-promtail
  namespace: {{ .Release.Namespace }} 