{{- if .Values.nfs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workload-log-pvc
  namespace: {{ .Release.Namespace | quote }}
spec:
  resources:
    requests:
      storage: {{ .Values.nfs.size | quote }}
  accessModes:
    {{- range .Values.nfs.accessModes }}
    - {{ . | quote }}
    {{- end }}
  storageClassName: {{ .Values.nfs.storageClassName }}
{{- end }}
