{{- if .Values.local.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workload-log-pvc
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  resources:
    requests:
      storage: {{ .Values.local.size | quote }}
  accessModes:
    {{- range .Values.local.accessModes }}
    - {{ . | quote }}
    {{- end }}
  storageClassName: {{ .Values.local.storageClassName }}
  selector:
    matchLabels:
      type: workload-log 
{{- end }}

