all:
  hosts:
    master1:
      ansible_host: 10.61.3.164
      ip: 10.61.3.164
      access_ip: 10.61.3.164
      ansible_user: root                # SSH 접속 계정
      #ansible_become: true
      #ansible_become_method: su
      #ansible_become_user: root
      #ansible_become_password: secret1 # node1의 root 비번

    master2:
      ansible_host: 10.61.3.165
      ip: 10.61.3.165
      access_ip: 10.61.3.165
      ansible_user: root
      #ansible_become: true
      #ansible_become_method: su
      #ansible_become_user: root
      #ansible_become_password: secret2 # node2의 root 비번

    master3:
      ansible_host: 10.61.3.168
      ip: 10.61.3.168
      access_ip: 10.61.3.168
      ansible_user: root
      #ansible_become: true
      #ansible_become_method: su
      #ansible_become_user: root
      #ansible_become_password: secret3 # node3의 root 비번

    dgx-b300:
      ansible_host: 10.61.3.10
      ip: 10.61.3.10
      access_ip: 10.61.3.10
      ansible_user: root
      #ansible_become: true
      #ansible_become_method: su
      #ansible_become_user: root
      #ansible_become_password: secret3 # node3의 root 비번

  children:
    kube_control_plane:
      hosts:
        master1:
        master2:
        master3:
    kube_node:
      hosts:
        DGXB300:
    etcd:
      hosts:
        master1:
        master2:
        master3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
