all:
  hosts:
    master-1:
      ansible_host: 10.61.3.161
      ip: 10.61.3.161
      access_ip: 10.61.3.161
      ansible_user: root                # SSH 접속 계정
      #ansible_become: true
      #ansible_become_method: su
      #ansible_become_user: root
      #ansible_become_password: secret1 # node1의 root 비번

    master-2:
      ansible_host: 10.61.3.162
      ip: 10.61.3.162
      access_ip: 10.61.3.162
      ansible_user: root
      #ansible_become: true
      #ansible_become_method: su
      #ansible_become_user: root
      #ansible_become_password: secret2 # node2의 root 비번

    worker-1:
      ansible_host: 10.61.3.22
      ip: 10.61.3.22
      access_ip: 10.61.3.22
      ansible_user: root
      #ansible_become: true
      #ansible_become_method: su
      #ansible_become_user: root
      #ansible_become_password: secret3 # node3의 root 비번

    worker-2:
      ansible_host: 10.61.3.24
      ip: 10.61.3.24
      access_ip: 10.61.3.24
      ansible_user: root
      #ansible_become: true
      #ansible_become_method: su
      #ansible_become_user: root
      #ansible_become_password: secret3 # node3의 root 비번

  children:
    kube_control_plane:
      hosts:
        master-1:
        master-2:
        worker-1:
    kube_node:
      hosts:
        worker-1:
        worker-2:
    etcd:
      hosts:
        master-1:
        master-2:
        worker-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
