apiVersion: v1
kind: Service
metadata:
  name: uyuni-backend-monitor
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector: 
    {{- include "backend.selectorLabels" . | nindent 4 }}
