{{- if .Values.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-keycloak-postgresql-0
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  resources:
    requests:
      storage: {{ .Values.size | quote }}
  accessModes:
    {{- range .Values.accessModes }}
    - {{ . | quote }}
    {{- end }}
  storageClassName: {{ .Values.storageClassName }} 
{{- end }}
