apiVersion: batch/v1
kind: Job
metadata:
  name: create-folder
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
      - name: create-folder
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - mkdir -p /mnt/host-folder/astrago-mariadb-volume /mnt/host-folder/keycloak-volume /mnt/host-folder/prometheus-volume /mnt/host-folder/workload-log-volume
        volumeMounts:
        - name: host-volume
          mountPath: /mnt/host-folder
      restartPolicy: Never
      volumes:
      - name: host-volume
        hostPath:
          path: {{ .Values.local.basePath }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.local.nodeName }}
