apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
data:
  redis.conf: |
    # Redis configuration
    bind 0.0.0.0
    port 6379
    
    # Memory management
    maxmemory {{ .Values.config.maxmemory }}
    maxmemory-policy {{ .Values.config.maxmemoryPolicy }}
    
    # Persistence
    save {{ .Values.config.save }}
    
    # Security
    {{- if .Values.auth.enabled }}
    requirepass ${REDIS_PASSWORD}
    {{- end }}
    
    # Logging
    loglevel notice
    
    # Network
    tcp-keepalive 300
    timeout 0
    
    # Other
    databases 16 