# Base environment values
# This file contains the base configuration for the current branch
# Content will vary based on branch: main (dev), stabilize (stage), release (prod)

# External Access Configuration (Single Source of Truth)
externalAccess:
  mode: "ip"  # "ip" or "domain"
  ip:
    address: ""  # LoadBalancer IP for ingress-nginx controller (user's actual access point)
    port: ""
  domain:
    name: ""
    tls:
      enabled: false
      issuer: ""  # cert-manager ClusterIssuer (e.g., "letsencrypt-prod") - leave empty to use existing Secret
      secretName: ""

# Volume Settings
nfs:
  storageClassName: astrago-nfs-csi
  server: 
  basePath: /kube_storage
  size: "10Gi" # PVC 기본 크기
  
# Keycloak Settings
keycloak:
  adminUser: admin
  adminPassword: xiirocks
  servicePort: 30001
  image:
    registry: "docker.io"
    repository: "xiilab/astrago-keycloak-theme"
    tag: "v1.2.0"

# Astrago Settings
astrago:
  baseUrl: "http://127.0.0.1:30080"  # 전체 외부 접근 URL (scheme://host:port)
  servicePort: 30080                 # NodePort (내부 서비스용)
  userInitPassword: astrago
  keycloak:
    baseUrl: ""  # If different from astrago.baseUrl, specify here (e.g., external Keycloak)
    realm: astrago
    client: astrago-client
    clientSecret: astragosecret
    userInitPassword: astrago
  mariadb:
    rootPassword: root
    username: astrago
    password: xiirocks
    maxLifetime: "1800000"

  # 이미지 기본 설정 (components에 적용)
  imageDefaults:
    registry: "ghcr.io"
    repository: "xiilab/astrago-backend"
    pullPolicy: "IfNotPresent"

  components:
    core:
      tag: "core-stage-c5ad"
    batch:
      tag: "batch-stage-c5ad"
    monitor:
      tag: "monitor-stage-c5ad"
    frontend:
      repository: "xiilab/astrago-frontend"  # Frontend는 별도 레포지토리 사용
      tag: "frontend-stage-3770"
  oneview:
    enabled: false

harbor:
  servicePort: 30002
  enabled: true
  adminPassword: Harbor12345

offline:
  registry: # 192.168.56.11:35000
  httpServer: # http://192.168.56.11