# Base environment values
# This file contains the base configuration for the current branch
# Content will vary based on branch: main (dev), stabilize (stage), release (prod)

# External Access Configuration (Single Source of Truth)
externalAccess:
  mode: "ip"  # "ip" or "domain"
  ip:
    address: ""  # Same as ingressNginx.loadBalancerIP (user's actual access point)
    port: ""
  domain:
    name: ""
    tls:
      enabled: false
      issuer: ""
      secretName: ""

# Volume Settings
nfs:
  storageClassName: astrago-nfs-csi
  server: 
  basePath: /kube_storage
  
# Keycloak Settings
keycloak:
  adminUser: admin
  adminPassword: xiirocks
  servicePort: 30001
  image:
    registry: "docker.io"
    repository: "xiilab/astrago-keycloak-theme"
    tag: "v1.2.0"
  ingress:
    enabled: true  # 고객 배포시 기본 활성화
    host: ""  # 빈 값이면 모든 IP/도메인에서 접근 허용 (고객별 설정)
    tls:
      enabled: false
      secretName: ""  # TLS 인증서 미사용

# Astrago Settings
astrago:
  baseUrl: "http://127.0.0.1:30080"  # 전체 외부 접근 URL (scheme://host:port)
  servicePort: 30080                 # NodePort (내부 서비스용)
  userInitPassword: astrago
  imageDefaults:
    registry: "docker.io"
    repository: "xiilab/astrago-posco"
    pullPolicy: "IfNotPresent"
  keycloak:
    baseUrl: ""  # If different from astrago.baseUrl, specify here (e.g., external Keycloak)
    realm: astrago
    client: astrago-client
    clientSecret: astragosecret
    userInitPassword: astrago
  mariadb:
    rootPassword: root
    username: astrago
    password: xiirocks
    maxLifetime: "1800000"
  components:
    core:
      tag: "core-stage-c5ad"
    batch:
      tag: "batch-stage-c5ad"
    monitor:
      tag: "monitor-stage-c5ad"
    frontend:
      tag: "frontend-stage-3770"
  oneview:
    enabled: false

harbor:
  servicePort: 30002
  enabled: true
  adminPassword: Harbor12345

# Astrago Ingress Settings (기본값)
ingress:
  enabled: true  # 고객 배포시 기본 활성화
  className: nginx
  host: ""  # 고객별로 도메인 설정
  tls:
    enabled: false
    secretName: ""
  # 환경별 추가 annotation 설정
  additionalAnnotations: {}
    # 예시: cert-manager + HTTPS 리다이렉트
    # cert-manager.io/cluster-issuer: "letsencrypt-staging"  # 또는 "letsencrypt-prod"
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # 다른 환경별 annotation도 여기서 추가 가능

# Ingress NGINX Settings
ingressNginx:
  loadBalancerIP:  # Will be set per customer environment

offline:
  registry: # 192.168.56.11:35000
  httpServer: # http://192.168.56.11