# Base environment values
# This file contains the base configuration for the current branch
# Content will vary based on branch: main (dev), stabilize (stage), release (prod)

# Volume Settings
nfs:
  storageClassName: astrago-nfs-csi
  server: 
  basePath: /kube_storage
  
# Keycloak Settings
keycloak:
  adminUser: admin
  adminPassword: xiirocks
  servicePort: 30001
  image:
    registry: "docker.io"
    repository: "xiilab/astrago-keycloak-theme"
    tag: "v1.2.0"
  ingress:
    enabled: true  # 고객 배포시 기본 활성화
    tls:
      enabled: false
      secretName: ""  # TLS 인증서 미사용

# Astrago Settings
astrago:
  baseUrl: "http://127.0.0.1:30080"  # 전체 외부 접근 URL (scheme://host:port)
  servicePort: 30080                 # NodePort (내부 서비스용)
  userInitPassword: astrago
  keycloak:
    baseUrl: ""  # If different from astrago.baseUrl, specify here (e.g., external Keycloak)
    realm: astrago
    client: astrago-client
    clientSecret: astragosecret
    userInitPassword: astrago
  mariadb:
    rootPassword: root
    username: astrago
    password: xiirocks
    maxLifetime: "1800000"
  core:
    registry: "docker.io"
    repository: "xiilab/astrago-posco"
    imageTag: "core-stage-c5ad"
  batch:
    registry: "docker.io"
    repository: "xiilab/astrago-posco"
    imageTag: "batch-stage-c5ad"
  monitor:
    registry: "docker.io"
    repository: "xiilab/astrago-posco"
    imageTag: "monitor-stage-c5ad"
  frontend:
    registry: "docker.io"
    repository: "xiilab/astrago-posco"
    imageTag: frontend-stage-3770
  oneview:
    enabled: false

harbor:
  servicePort: 30002
  enabled: true
  adminPassword: Harbor12345

# Astrago Ingress Settings (기본값)
ingress:
  enabled: true  # 고객 배포시 기본 활성화
  className: nginx
  host: ""  # 고객별로 도메인 설정
  tls:
    enabled: false
    secretName: ""
    clusterIssuer: ""  # cert-manager ClusterIssuer (예: "letsencrypt-prod", "letsencrypt-staging")
  # 환경별 추가 annotation 설정
  additionalAnnotations:
    # cert-manager annotation (clusterIssuer가 설정된 경우에만 적용)
    # 다른 환경별 annotation도 여기서 추가 가능

# Ingress NGINX Settings
ingressNginx:
  loadBalancerIP:  # Will be set per customer environment

offline:
  registry: # 192.168.56.11:35000
  httpServer: # http://192.168.56.11