# GPU Process Exporter Configuration
# Exports GPU process metrics to Prometheus via HTTP API + ServiceMonitor

gpu-process-exporter:
  enabled: true

# HTTP Server settings
httpServer:
  # Port for metrics endpoint
  port: 8080
  # Metrics collection interval (seconds)
  interval: 30
  
  # Image settings
  image:
    repository: busybox
    tag: "1.35"
    pullPolicy: IfNotPresent
  
  # Resource limits
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Service configuration
service:
  enabled: true
  type: ClusterIP
  port: 8080
  targetPort: 8080
  labels: {}
  annotations: {}

# ServiceMonitor configuration for Prometheus Operator
serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  labels: {}
  # Selector labels for the service
  selector:
    matchLabels:
      app: gpu-process-exporter

# GPU configuration
gpu:
  # Number of GPUs to monitor (adjust based on your cluster)
  count: 4
  # GPU device indices to monitor
  devices: [0, 1, 2, 3]

# Node selection
nodeSelector:
  nvidia.com/gpu.present: "true"

# Tolerations for GPU nodes
tolerations:
- key: nvidia.com/gpu
  operator: Exists
  effect: NoSchedule 