apiVersion: v1
kind: ConfigMap
metadata:
  name: helmfile-plugin-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: plugin
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: helmfile
    spec:
      generate:
        command: ["helmfile"]
        args: ["template", "--include-crds", "-l", "argocd=true"]
      discover:
        fileName: "helmfile.yaml.gotmpl"