apiVersion: v1
kind: ConfigMap
metadata:
  name: helmfile-plugin-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: plugin
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: helmfile
    spec:
      generate:
        command: ["sh", "-c"]
        args: ["helmfile -e ${ARGOCD_ENV_HELMFILE_ENVIRONMENT:-default} template --include-crds -l argocd=true --include-needs"]
      discover:
        fileName: "helmfile.yaml.gotmpl"