# ArgoCD 최신 버전 최소 설정 with Helmfile Plugin

configs:
  cm:
    url: https://argocd.xiilab.com:30011
    exec.enabled: "true"
    server.enable.proxy.extension: "true"

server:
  service:
    type: NodePort
    nodePortHttp: 30010
    nodePortHttps: 30011
  extraArgs:
    - --enable-proxy-extension

repoServer:
  extraContainers:
    - name: cmp-helmfile
      image: ghcr.io/travisghansen/argo-cd-helmfile:v0.3.13
      command: ["/var/run/argocd/argocd-cmp-server"]
      securityContext: { runAsNonRoot: true, runAsUser: 999 }
      volumeMounts:
        - name: var-files
          mountPath: /var/run/argocd
        - name: cmp-tmp
          mountPath: /tmp
        - name: helmfile-plugin-cm
          mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: plugin.yaml
        - name: plugins
          mountPath: /home/argocd/cmp-server/plugins
  volumes:
    - name: helmfile-plugin-cm
      configMap: { name: helmfile-plugin-cm }
    - name: plugins
      emptyDir: {}
    - name: cmp-tmp
      emptyDir: {}