- name: Install offline yum repo
  yum_repository:
    file: offline
    name: offline-repo
    description: Offline repo for kubespray
    baseurl: "{{ yum_repo }}/local"
    enabled: yes
    gpgcheck: no
