{{- if .Values.psp.enabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: nvidia-network-operator-privileged
  labels:
    {{- include "network-operator.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: "restricted denies access to all host features and requires
      pods to be run with a UID, read-only root filesystem and SELinux context that are
      allocated to the namespace."
spec:
  privileged: true
  hostIPC: false
  hostNetwork: true
  hostPID: false
  allowPrivilegeEscalation: true
  readOnlyRootFilesystem: false
  allowedHostPaths: []
  allowedCapabilities:
    - '*'
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - configMap
    - hostPath
    - secret
    - downwardAPI
{{- end }}
