gpu-operator:
  dcgmExporter:
    enabled: true
    repository: nvcr.io/nvidia/k8s
    image: dcgm-exporter
    version: 3.3.0-3.2.0-ubuntu22.04
    imagePullPolicy: IfNotPresent
    config:
      name: metrics-config
    env:
      - name: DCGM_EXPORTER_LISTEN
        value: ":9400"
      - name: DCGM_EXPORTER_KUBERNETES
        value: "true"
      - name: DCGM_EXPORTER_COLLECTORS
        value: "/etc/dcgm-exporter/dcgm-metrics.csv"

  driver:
    enabled: false

  toolkit:
    enabled: true 

  migManager:
    enabled: true
    config:
      name: "custom-mig-parted-config"
      default: "all-disabled"
    env:
      - name: WITH_REBOOT
        value: "true"

  mig:
    strategy: single

#  devicePlugin:
#    config:
#      name: "nvidia-plugin-configs-mps"
