all:
  hosts:
    node1:
      ansible_host: 10.61.3.123
      ip: 10.61.3.123
      access_ip: 10.61.3.123
      ansible_user: root                # SSH 접속 계정
      #ansible_become: true
      #ansible_become_method: su
      #ansible_become_user: root
      #ansible_become_password: secret1 # node1의 root 비번

    node2:
      ansible_host: 10.61.3.124
      ip: 10.61.3.124
      access_ip: 10.61.3.124
      ansible_user: root
      #ansible_become: true
      #ansible_become_method: su
      #ansible_become_user: root
      #ansible_become_password: secret2 # node2의 root 비번

    node3:
      ansible_host: 10.61.3.125
      ip: 10.61.3.125
      access_ip: 10.61.3.125
      ansible_user: root
      #ansible_become: true
      #ansible_become_method: su
      #ansible_become_user: root
      #ansible_become_password: secret3 # node3의 root 비번

  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}