#repositories:
#- name: csi-driver-nfs
#  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
#- name: volcano-sh 
#  url: https://volcano-sh.github.io/helm-charts
#- name: fluxcd-community
#  url: fluxcd-community https://fluxcd-community.github.io/helm-charts
#- name: nvidia
#  url: https://nvidia.github.io/gpu-operator
#- name: grafana
#  url: https://grafana.github.io/helm-charts
#- name: prometheus-community
#  url: https://prometheus-community.github.io/helm-charts
#- name: keycloak
#  url: oci://registry-1.docker.io/bitnamicharts/keycloak
#- name: kubeflow
#  url: https://kubeflow.github.io/helm-charts
#- name: harbor
#  url: https://helm.goharbor.io

environments:
  prod:
    values:
    - environments/common/values.yaml
    - environments/prod/values.yaml
  dev:
    values:
    - environments/common/values.yaml
    - environments/dev/values.yaml
  dev2:
    values:
    - environments/common/values.yaml
    - environments/dev2/values.yaml
  stage:
    values:
    - environments/common/values.yaml
    - environments/stage/values.yaml
  seoultech:
    values:
    - environments/common/values.yaml
    - environments/seoultech/values.yaml
  astrago:
    values:
    - environments/common/values.yaml
    - environments/astrago/values.yaml

helmDefaults:
  wait: true
  waitForJobs: true
  timeout: 600
  createNamespace: true

releases:
- name: nfs-provisioner
  namespace: nfs-provisioner
  chart: charts/csi-driver-nfs
  version: v4.7.0
  labels:
    app: nfs-provisioner
  values:
  - values/csi-driver-nfs/values.yaml.gotmpl

- name: gpu-operator
  namespace: gpu-operator
  chart: charts/gpu-operator
  version: v24.9.2
  labels:
    app: gpu-operator
    type: infra
  values:
  - values/gpu-operator/values.yaml.gotmpl

- name: gpu-operator-extras
  namespace: gpu-operator
  chart: charts/gpu-operator-extras
  version: 1.0.0
  labels:
    app: gpu-operator
    type: infra
  needs:
  - gpu-operator

- name: gpu-process-exporter
  chart: charts/gpu-process-exporter
  namespace: gpu-operator
  version: 1.0.0
  labels:
    app: gpu-process-exporter
  values:
  - values/gpu-process-exporter/values.yaml.gotmpl

- name: volcano
  namespace: volcano-system
  chart: charts/volcano
  version: 1.12.1
  labels:
    app: volcano
  values:
  - values/volcano/values.yaml

- name: volcano-vgpu-device-plugin
  namespace: volcano-system
  chart: charts/volcano-vgpu-device-plugin
  version: 1.0.0
  labels:
    app: volcano
  needs:
  - volcano    

- name: flux
  namespace: flux
  chart: charts/flux2
  version: 2.13.0
  labels:
    app: flux
  values:
  - values/flux/values.yaml.gotmpl

- name: loki-stack
  namespace: loki-stack
  chart: charts/loki-stack
  version: 1.0.0
  labels:
    app: loki-stack
    component: logging
  values:
  - values/loki-stack/values.yaml.gotmpl
  needs:
  - nfs-provisioner/nfs-provisioner

- name: prometheus
  namespace: prometheus
  chart: charts/kube-prometheus-stack
  version: 55.4.0
  labels:
    app: prometheus
  values:
  - values/kube-prometheus-stack/values.yaml.gotmpl
  needs:
  - nfs-provisioner/nfs-provisioner

- name: keycloak
  namespace: keycloak
  chart: charts/keycloak
  version: 17.3.5
  labels:
    app: keycloak
  values:
  - values/keycloak/values.yaml.gotmpl
  needs:
  - nfs-provisioner/nfs-provisioner

- name: keycloak-extras
  namespace: keycloak
  chart: charts/keycloak-extras
  version: 1.0.0
  labels:
    app: keycloak
  needs:
  - keycloak

- name: mpi-operator
  chart: charts/mpi-operator
  version: 0.1.0
  labels:
    app: mpi-operator
  values:
  - values/mpi-operator/values.yaml.gotmpl

- name: harbor
  namespace: harbor
  chart: charts/harbor
  version: 1.15.1
  condition: harbor.enabled
  labels:
    app: harbor
  values:
  - values/harbor/values.yaml.gotmpl
  needs:
  - nfs-provisioner/nfs-provisioner

- name: astrago
  namespace: astrago
  chart: charts/astrago
  version: 0.1.0
  labels:
    app: astrago
  values:
  - values/astrago/values.yaml.gotmpl
  needs:
  - nfs-provisioner/nfs-provisioner
  - keycloak/keycloak
