annotations:
  category: DeveloperTools
  images: |
    - name: keycloak-config-cli
      image: docker.io/bitnami/keycloak-config-cli:5.9.0-debian-11-r1
    - name: keycloak
      image: docker.io/bitnami/keycloak:22.0.5-debian-11-r2
  licenses: Apache-2.0
apiVersion: v2
appVersion: 22.0.5
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: file://charts/postgresql
  version: 13.x.x
- name: common
  repository: file://charts/common
  tags:
  - bitnami-common
  version: 2.x.x
description: Keycloak is a high performance Java-based identity and access management
  solution. It lets developers add an authentication layer to their applications with
  minimum effort.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/keycloak/img/keycloak-stack-220x234.png
keywords:
- keycloak
- access-management
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: keycloak
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/keycloak
version: 17.3.5
