# externalIP:
externalIP: 10.61.3.12
# Volume Settings
nfs:
  storageClassName: astrago-nfs-csi
  server: 10.61.3.2
  basePath: /kube_storage/develop-astrago

# GPU Process Exporter Settings
gpu-process-exporter:
  enabled: true
  collection:
    schedule: "*/1 * * * *" # Every minute
    image:
      repository: busybox
      tag: "1.35"
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 32Mi
  prometheus:
    serverService: prometheus-kube-prometheus-prometheus.prometheus.svc:9090
  gpu:
    count: 4
    devices: [0, 1, 2, 3]
  nodeSelector:
    nvidia.com/gpu.present: "true"
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule

# Keycloak Settings
keycloak:
  adminUser: admin
  adminPassword: xiirocks
  servicePort: 30001
# Astrago Settings
astrago:
  proxyUrl: https://10.61.3.12
  servicePort: 30080
  userInitPassword: astrago
  keycloak:
    externalKeycloakUrl:
    realm: astrago
    client: astrago-client
    clientSecret: astragosecret
    userInitPassword: astrago
  mariadb:
    rootPassword: root
    username: astrago
    password: xiirocks
    maxLifetime: "3595000"
  mongodb:
    url: mongodb://astrago:xiirocks@astrago-mongodb:27017/astrago?authSource=admin
  core:
    registry: "harbor.xiilab.com:32080"
    repository: "astrago/core"
    imageTag: "dev-3eff"
  batch:
    registry: "harbor.xiilab.com:32080"
    repository: "astrago/batch"
    imageTag: "dev-3eff"
  monitor:
    registry: "harbor.xiilab.com:32080"
    repository: "astrago/monitor"
    imageTag: "dev-3eff"
  frontend:
    registry: "harbor.xiilab.com:32080"
    repository: "astrago/frontend"
    imageTag: dev-889b
  experiment:
    registry: "harbor.xiilab.com:32080"
    repository: "astrago/experiment"
    imageTag: "dev-3eff"
  oneview:
    enabled: true
# Loki Settings
loki:
  replicas: 1
  resources:
    limits:
      cpu: "1000m"
      memory: "2Gi"
    requests:
      cpu: "500m"
      memory: "1Gi"
  persistence:
    enabled: true
    size: "20Gi"
    storageClass: "astrago-nfs-csi"
  retention:
    enabled: true
    period: "168h" # 7 days for dev environment
    compaction_interval: "10m"
    delete_delay: "2h"
    delete_worker_count: 150
  gpu:
    count: 4
    devices: [0, 1, 2, 3]
  nodeSelector:
    nvidia.com/gpu.present: "true"
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule

# Promtail Settings
promtail:
  resources:
    limits:
      cpu: "200m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"

harbor:
  enabled: true
  servicePort: 30002
  adminPassword: Harbor12345
offline:
  registry: # 192.168.56.11:35000
  httpServer: # http://192.168.56.11
