apiVersion: v2
name: loki-stack
description: Complete logging solution with Loki and Promtail using local charts
type: application
version: 1.0.0
appVersion: "2.9.6"

# No external dependencies - everything will be defined locally 