apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: astrago-stabilize
  namespace: argocd
  labels:
    app.kubernetes.io/name: astrago
    app.kubernetes.io/component: main
    astrago.io/environment: staging
    astrago.io/branch: stabilize-1.0
spec:
  project: default
  
  # 현재 저장소의 helmfile 사용
  source:
    repoURL: https://github.com/xiilab/astrago-deployment.git
    targetRevision: stabilize/1.0
    path: helmfile
    plugin:
      name: helmfile
      env:
        - name: HELMFILE_ENVIRONMENT
          value: "staging"
        - name: LABEL_KEY
          value: "app"
        - name: LABEL_VALUE
          value: "astrago"
  
  destination:
    server: https://10.61.3.161:6443
