apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: astrago-staging
  namespace: argocd
  labels:
    app.kubernetes.io/name: astrago
    app.kubernetes.io/component: main
    astrago.io/environment: staging
    astrago.io/branch: stabilize-1.0
spec:
  project: default
  
  # 현재 저장소의 helmfile 사용
  source:
    repoURL: https://github.com/xiilab/astrago-deployment.git
    targetRevision: stabilize/1.0
    path: helmfile
    plugin:
      name: helmfile
      env:
        - name: HELMFILE_ENVIRONMENT
          value: "xiilab"
  destination:
    server: https://10.61.3.161:6443
  syncPolicy:
    automated:
      prune: true                  # Git에서 지워지면 클러스터에서도 삭제
      selfHeal: true               # 드리프트 자동 복구
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true    
