#repositories:
#  - name: nfs-provisioner 
#    url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
#
releases:
- name: nfs-provisioner
  namespace: "kube-system"
  chart: csi-driver-nfs
  condition: nfs.enabled
  wait: true
  labels:
    app: nfs-provisioner
  values:
  - values.yaml.gotmpl

- name: storage-class
  namespace: "kube-system"
  chart: storage-class
  wait: true
  labels:
    app: nfs-provisioner
  values:
  - values.yaml.gotmpl  
