apiVersion: v1
kind: Service
metadata:
  name: uyuni-frontend
  namespace: uyuni
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
