apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki-stack.fullname" . }}-loki-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki-stack.labels" . | nindent 4 }}
    app: loki
    component: loki
data:
  loki.yaml: |
    auth_enabled: false
    
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      grpc_server_max_recv_msg_size: 33554432  # 32MB
      grpc_server_max_send_msg_size: 33554432  # 32MB
      http_server_read_timeout: 30s
      http_server_write_timeout: 30s
      
    common:
      instance_addr: 127.0.0.1
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
          
    distributor:
      ring:
        kvstore:
          store: inmemory
      
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s
      max_transfer_retries: 0
      max_chunk_age: 10m
      chunk_target_size: 1536000  # 1.5MB
      chunk_encoding: snappy
      
    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: {{ .Values.loki.config.query_cache_size | default 128 }}
            ttl: 24h
      align_queries_with_step: true
      max_retries: 3
      parallelise_shardable_queries: true
      cache_results: true
      
    query_scheduler:
      max_outstanding_requests_per_tenant: 1024
      
    querier:
      max_concurrent: 10
      query_timeout: 300s
      
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
            
    ruler:
      alertmanager_url: http://localhost:9093
      
    {{- if .Values.loki.config.table_manager }}
    table_manager:
      retention_deletes_enabled: {{ .Values.loki.config.table_manager.retention_deletes_enabled | default false }}
      retention_period: {{ .Values.loki.config.table_manager.retention_period | default "720h" | quote }}
    {{- end }}
    
    {{- if .Values.loki.config.compactor }}
    compactor:
      working_directory: {{ .Values.loki.config.compactor.working_directory | default "/loki/compactor" | quote }}
      shared_store: {{ .Values.loki.config.compactor.shared_store | default "filesystem" | quote }}
      compaction_interval: {{ .Values.loki.config.compactor.compaction_interval | default "10m" | quote }}
      retention_enabled: {{ .Values.loki.config.compactor.retention_enabled | default false }}
      retention_delete_delay: {{ .Values.loki.config.compactor.retention_delete_delay | default "2h" | quote }}
      retention_delete_worker_count: {{ .Values.loki.config.compactor.retention_delete_worker_count | default 150 }}
    {{- end }}
    
    limits_config:
      reject_old_samples: false
      reject_old_samples_max_age: 168h
      ingestion_rate_mb: {{ .Values.loki.config.ingestion_rate_mb | default 32 }}
      ingestion_burst_size_mb: {{ .Values.loki.config.ingestion_burst_size_mb | default 64 }}
      max_streams_per_user: {{ .Values.loki.config.max_streams_per_user | default 20000 }}
      max_line_size: {{ .Values.loki.config.max_line_size | default "256KB" | quote }}
      max_entries_limit_per_query: {{ .Values.loki.config.max_entries_limit_per_query | default 5000 }}
      max_global_streams_per_user: {{ .Values.loki.config.max_global_streams_per_user | default 30000 }}
      max_query_length: {{ .Values.loki.config.max_query_length | default "12000h" | quote }}
      max_query_parallelism: {{ .Values.loki.config.max_query_parallelism | default 16 }}
      max_query_series: {{ .Values.loki.config.max_query_series | default 5000 }}
      max_label_name_length: 1024
      max_label_value_length: 4096
      max_label_names_per_series: 30
      per_stream_rate_limit: {{ .Values.loki.config.per_stream_rate_limit | default "10MB" | quote }}
      per_stream_rate_limit_burst: {{ .Values.loki.config.per_stream_rate_limit_burst | default "20MB" | quote }}
      {{- if .Values.loki.config.limits_config }}
      retention_period: {{ .Values.loki.config.limits_config.retention_period | default "720h" | quote }}
      {{- end }}
      
    frontend:
      max_outstanding_per_tenant: 1024
      compress_responses: true
      
    frontend_worker:
      frontend_address: 127.0.0.1:9095
      grpc_client_config:
        max_send_msg_size: 33554432  # 32MB 