apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki-stack.fullname" . }}-promtail-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki-stack.labels" . | nindent 4 }}
    app: promtail
    component: promtail
data:
  config.yaml: |
    server:
      http_listen_port: 3101
      grpc_listen_port: 0
      
    positions:
      filename: /run/promtail/positions.yaml
      
    clients:
      - url: http://{{ include "loki-stack.fullname" . }}-loki.{{ .Release.Namespace }}.svc.cluster.local:3100/loki/api/v1/push
        
    scrape_configs:
      # Kubernetes Pods - containerd 표준 경로 (/var/log/pods)
      - job_name: kubernetes-pods-containerd
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - regex:
              expression: '^(?P<timestamp>\S+) (?P<stream>stdout|stderr) (?P<flag>\S+) (?P<content>.*)$'
          - timestamp:
              source: timestamp
              format: RFC3339Nano
          - output:
              source: content
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_controller_name
            regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
            action: replace
            target_label: __tmp_controller_name
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_name
              - __meta_kubernetes_pod_label_app
              - __tmp_controller_name
              - __meta_kubernetes_pod_name
            regex: ^([^;]+).*|^;([^;]+).*|^;;([^;]+).*|^;;;(.+)$
            action: replace
            replacement: $1$2$3$4
            target_label: app
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_instance
              - __meta_kubernetes_pod_label_instance
            regex: ^;*([^;]+)(;.*)?$
            action: replace
            target_label: instance
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_component
              - __meta_kubernetes_pod_label_component
            regex: ^;*([^;]+)(;.*)?$
            action: replace
            target_label: component
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_node_name
            target_label: node_name
          - action: replace
            source_labels:
            - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            replacement: $1
            separator: /
            source_labels:
            - namespace
            - app
            target_label: job
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_container_name
            target_label: container
          - action: replace
            replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
            - __meta_kubernetes_pod_uid
            - __meta_kubernetes_pod_container_name
            target_label: __path__
          - action: replace
            replacement: containerd
            target_label: container_runtime

      # Kubernetes Pods - CRI-O 경로 (/var/log/crio/pods)
      - job_name: kubernetes-pods-crio
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - regex:
              expression: '^(?P<timestamp>\S+) (?P<stream>stdout|stderr) (?P<flag>\S+) (?P<content>.*)$'
          - timestamp:
              source: timestamp
              format: RFC3339Nano
          - output:
              source: content
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_controller_name
            regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
            action: replace
            target_label: __tmp_controller_name
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_name
              - __meta_kubernetes_pod_label_app
              - __tmp_controller_name
              - __meta_kubernetes_pod_name
            regex: ^([^;]+).*|^;([^;]+).*|^;;([^;]+).*|^;;;(.+)$
            action: replace
            replacement: $1$2$3$4
            target_label: app
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_instance
              - __meta_kubernetes_pod_label_instance
            regex: ^;*([^;]+)(;.*)?$
            action: replace
            target_label: instance
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_component
              - __meta_kubernetes_pod_label_component
            regex: ^;*([^;]+)(;.*)?$
            action: replace
            target_label: component
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_node_name
            target_label: node_name
          - action: replace
            source_labels:
            - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            replacement: $1
            separator: /
            source_labels:
            - namespace
            - app
            target_label: job
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_container_name
            target_label: container
          - action: replace
            replacement: /var/log/crio/pods/*$1/*.log
            separator: /
            source_labels:
            - __meta_kubernetes_pod_uid
            - __meta_kubernetes_pod_container_name
            target_label: __path__
          - action: replace
            replacement: crio
            target_label: container_runtime

      # 컨테이너 로그 - 추가 경로 (/var/log/containers)
      - job_name: kubernetes-containers-legacy
        static_configs:
          - targets: [localhost]
            labels:
              job: kubernetes-containers
              __path__: /var/log/containers/*.log
        pipeline_stages:
          - regex:
              expression: '^(?P<timestamp>\S+) (?P<stream>stdout|stderr) (?P<flag>\S+) (?P<content>.*)$'
          - timestamp:
              source: timestamp
              format: RFC3339Nano
          - output:
              source: content
          - regex:
              expression: '^/var/log/containers/(?P<pod_name>[^_]+)_(?P<namespace>[^_]+)_(?P<container_name>[^-]+)-(?P<container_id>[^.]+)\.log$'
              source: filename
          - labels:
              pod: pod_name
              namespace: namespace
              container: container_name
              container_runtime: legacy 