version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: airgap-nginx
    ports:
    - "28080:80"
    volumes:
    - ./offline-files:/usr/share/nginx/html/download
    - ./nginx.conf:/etc/nginx/nginx.conf

  registry:
    image: registry:latest
    container_name: airgap-registry
    ports:
    - "25000:5000"
    volumes:
    - ./registry:/var/lib/registry
