# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
    # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

            # Runs a single command using the runners shell
      - name: install helmfile and yq
        run: |
          # Install helmfile
          wget https://github.com/helmfile/helmfile/releases/download/v0.159.0/helmfile_0.159.0_linux_amd64.tar.gz -P /tmp/
          tar -zxvf /tmp/helmfile_0.159.0_linux_amd64.tar.gz -C /tmp/
          chmod +x /tmp/helmfile
          mv /tmp/helmfile /usr/local/bin
          
          # Install yq
          wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      # Update Keycloak image tag with latest commit hash
      - name: Update Keycloak image tag
        run: |
          # Get latest commit hash tag from Docker Hub (excluding 'latest')
          LATEST_TAG=$(curl -s "https://registry.hub.docker.com/v2/repositories/xiilab/astrago-keycloak-theme/tags/" | jq -r '.results[] | select(.name != "latest") | .name' | head -1)
          
          if [ -z "$LATEST_TAG" ]; then
            echo "No commit hash tag found, using latest"
            LATEST_TAG="latest"
          fi
          
          echo "Latest Keycloak image tag: $LATEST_TAG"
          
          # Update dev environment values
          if [ -f "environments/dev/values.yaml" ]; then
            yq eval '.keycloak.image.repository = "xiilab/astrago-keycloak-theme"' -i environments/dev/values.yaml
            yq eval ".keycloak.image.tag = \"$LATEST_TAG\"" -i environments/dev/values.yaml
            yq eval '.keycloak.image.pullPolicy = "Always"' -i environments/dev/values.yaml
            echo "Updated dev environment with tag: $LATEST_TAG"
          fi

      # Runs a set of commands using the runners shell
      - name: Run a dev monochart template script
        run: |
          helmfile -e dev -l app=astrago template > monochart/develop/astrago/astrago.yaml
          helmfile -e dev -l app=prometheus template --include-crds > monochart/develop/prometheus/prometheus.yaml
          helmfile -e dev -l app=keycloak template > monochart/develop/keycloak/keycloak.yaml
          helmfile -e dev -l app=nfs-provisioner template > monochart/develop/nfs-provisioner/nfs-provisioner.yaml
          helmfile -e dev -l app=gpu-operator -n gpu-operator template --include-crds > monochart/develop/gpu-operator/gpu-operator.yaml

      # Runs a set of commands using the runners shell
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: commit monochart.yaml
