# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
    # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: install helmfile
        run: |
          wget https://github.com/helmfile/helmfile/releases/download/v0.159.0/helmfile_0.159.0_linux_amd64.tar.gz -P /tmp/
          tar -zxvf /tmp/helmfile_0.159.0_linux_amd64.tar.gz -C /tmp/
          chmod +x /tmp/helmfile
          mv /tmp/helmfile /usr/local/bin

      # Runs a set of commands using the runners shell
      - name: Run stage monochart template script
        run: |
          helmfile -e stage -l app=astrago template > monochart/stage/astrago/astrago.yaml
          helmfile -e stage -l app=prometheus template --include-crds > monochart/stage/prometheus/prometheus.yaml
          helmfile -e stage -l app=keycloak template > monochart/stage/keycloak/keycloak.yaml
          helmfile -e stage -l app=nfs-provisioner template > monochart/stage/nfs-provisioner/nfs-provisioner.yaml
          helmfile -e stage -l app=gpu-operator -n gpu-operator template --include-crds > monochart/stage/gpu-operator/gpu-operator.yaml
          helmfile -e stage -l app=mpi-operator template > monochart/stage/mpi-operator/mpi-operator.yaml
          
      # Runs a set of commands using the runners shell
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: commit monochart.yaml
