nfs:
  server: 10.61.3.2
  share: /kube_storage
uyuni:
  nodePort: 30100
  keycloakUrl: http://192.168.1.235:30051/auth
  namespace: uyuni
  storageClass: nfs-csi
  mariadb:
    auth:
      rootPassword: root
      database: uyuni
      username: uyuni
      password: xiirocks
      replicationUser: replicator
      replicationPassword: ''
  core:
    repository: harbor.xiilab.com:32443/uyuni/server-core
    imageTag: "develop-79a0021"
  batch:
    repository: harbor.xiilab.com:32443/uyuni/server-batch
    imageTag: "develop-79a0021"
  monitor:
    repository: harbor.xiilab.com:32443/uyuni/server-monitor
    imageTag: "develop-79a0021"
  frontend:
    repository: "harbor.xiilab.com:32443/uyuni/uyuni-frontend"
    imageTag: develop-19beb90
    service:
      type: NodePort
      port: 3000
      nodePort: 30080
    env:
      - name: KEYCLOAK_HOST
        value: https://10.61.3.8:30002
      - name: KEYCLOAK_REALME
        value: myrealm
      - name: KEYCLOAK_CLIENT_ID
        value: kubernetes-client
      - name: AUTH_CLIENT_SECRET
        value: 7bE2Oq2HyKrPsX49EXul0G48O4c4kkFv
      - name: NEXTAUTH_URL
        value: http://localhost:3000
      - name: NEXTAUTH_SECRET
        value: uuNj1L0Yg2xKcBPVp7yOVlm2nigL3hoHOzbwQXAwx1I=
      - name: NEXT_PUBLIC_API_URL
        value: http://localhost:4444/
