common:
  externalIP: 10.61.3.12
  volume:
    volumeType: nfs
    nfs:
      storageClassName: astrago-nfs-csi
      server: 10.61.3.2
      basePath: /kube_storage/develop-astrago
keycloak:
  themeVersion: v1.0.13
  adminUser: admin
  adminPassword: xiirocks
  servicePort: 30001
prometheus:
  createVolume:
    enabled: true
    name: prometheus-volume
    size: 50Gi
    volumeType: nfs
    nfs:
      server: 10.61.3.2
      path: /kube_storage/develop-prometheus-volume
astrago:
  servicePort: 30080
  userInitPassword: astrago
  keycloak:
    realm: astrago
    client: astrago-client
    clientSecret: astragosecret
    userInitPassword: astrago
  mariadb:
    rootPassword: root
    username: astrago
    password: xiirocks
    maxLifetime: "3595000"
  createVolume:
    mariadb:
      enabled: true
      name: astra-mariadb-volume
      size: 8Gi
      volumeType: nfs
      nfs:
        server: 10.61.3.2
        path: /kube_storage/astra-mariadb-volume
    workloadLog:
      enabled: true
      name: astrago-workload-log
      size: 8Gi
      volumeType: nfs
      nfs:
        server: 10.61.3.2
        path: /kube_storage/astrago-log-volume
  core:
    repository: "harbor.xiilab.com:32443/uyuni/server-core"
    imageTag: "develop-f8da486"
  batch:
    repository: "harbor.xiilab.com:32443/uyuni/server-batch"
    imageTag: "develop-f8da486"
  monitor:
    repository: "harbor.xiilab.com:32443/uyuni/server-monitor"
    imageTag: "develop-f8da486"
  frontend:
    repository: "harbor.xiilab.com:32443/uyuni/uyuni-frontend"
    imageTag: develop-7e3aaf4
