# externalIP: 
externalIP: 10.61.3.12
# Volume Settings
nfs:
  enabled: true
  storageClassName: astrago-nfs-csi
  server: 10.61.3.2
  basePath: /kube_storage/develop-astrago
local:
  enabled: false
  storageClassName: astrago-local-storage
  nodeName:
  basePath:
# Keycloak Settings
keycloak:
  adminUser: admin
  adminPassword: xiirocks
  servicePort: 30001
# Astrago Settings
astrago:
  proxyUrl:
  servicePort: 30080
  userInitPassword: astrago
  keycloak:
    externalKeycloakUrl:
    realm: astrago
    client: astrago-client
    clientSecret: astragosecret
    userInitPassword: astrago
  mariadb:
    rootPassword: root
    username: astrago
    password: xiirocks
    maxLifetime: "3595000"
  core:
    registry: "harbor.xiilab.com:32443"
    repository: "harbor.xiilab.com:32443/astrago/core"
    imageTag: "dev-3685"
  batch:
    registry: "harbor.xiilab.com:32443"
    repository: "harbor.xiilab.com:32443/astrago/batch"
    imageTag: "dev-3685"
  monitor:
    registry: "harbor.xiilab.com:32443"
    repository: "harbor.xiilab.com:32443/astrago/monitor"
    imageTag: "dev-3685"
  frontend:
    registry: "harbor.xiilab.com:32443"
    repository: "harbor.xiilab.com:32443/astrago/frontend"
    imageTag: dev-d3c6
offline:
  registry: # 192.168.56.11:35000
  httpServer: # http://192.168.56.11
