# externalIP: 
externalIP: 10.61.3.12

# Volume Settings
nfs:
  enabled: false
  storageClassName: astrago-nfs-csi
  server: 10.61.3.2
  basePath: /kube_storage/develop-astrago
local:
  enabled: false
  storageClassName: local-storage
  nodeName: worker-1
  basePath: /astrago/data

# Keycloak Settings
keycloak:
  themeVersion: v1.0.13
  adminUser: admin
  adminPassword: xiirocks
  servicePort: 30001

# Astrago Settings
astrago:
  servicePort: 30080
  userInitPassword: astrago
  keycloak:
    realm: astrago
    client: astrago-client
    clientSecret: astragosecret
    userInitPassword: astrago
  mariadb:
    rootPassword: root
    username: astrago
    password: xiirocks
    maxLifetime: "3595000"
  core:
    repository: "harbor.xiilab.com:32443/uyuni/server-core"
    imageTag: "develop-03455da"
  batch:
    repository: "harbor.xiilab.com:32443/uyuni/server-batch"
    imageTag: "develop-03455da"
  monitor:
    repository: "harbor.xiilab.com:32443/uyuni/server-monitor"
    imageTag: "develop-03455da"
  frontend:
    repository: "harbor.xiilab.com:32443/uyuni/uyuni-frontend"
    imageTag: develop-ab78253
