nfs:
  server: 10.61.3.2
  share: /kube_storage
keycloak:
  repository: harbor.xiilab.com:32443/uyuni/server-core
  imageTag: "develop-0ff3d31"
uyuni:
  nodePort: 30100
  keycloakUrl: http://192.168.1.235:30051/auth
  namespace: uyuni
  storageClass: nfs-csi
  mariadb:
    auth:
      rootPassword: root
      database: uyuni
      username: uyuni
      password: xiirocks
      replicationUser: replicator
      replicationPassword: ''
  core:
    repository: harbor.xiilab.com:32443/uyuni/server-core
    imageTag: "develop-82e64ba"
    service:
      type: NodePort
      port: 8080
      nodePort: 30082
    env:
      - name: SPRING_DATASOURCE_URL
        value: jdbc:mariadb://mariadb:3306/uyuni
      - name: SPRING_DATASOURCE_USERNAME
        value: uyuni
      - name: SPRING_DATASOURCE_PASSWORD
        value: xiirocks
      - name: SPRING_SECURITY_OAUTH2_RESOURCE-SERVER_JWT_ISSUER-URI
        value: http://10.61.3.8:30001/realms/myrealm
      - name: SPRING_SECURITY_OAUTH2_RESOURCE-SERVER_JWK-SET-URI
        value: http://10.61.3.8:30001/realms/myrealm/protocol/openid-connect/certs
  batch:
    repository: harbor.xiilab.com:32443/uyuni/server-batch
    imageTag: "develop-82e64ba"
  monitor:
    repository: harbor.xiilab.com:32443/uyuni/server-monitor
    imageTag: "develop-82e64ba"
    service:
      type: NodePort
      port: 8080
      nodePort: 30081
    env:
      - name: SPRING_MVC_PATHMATCH_MATCHING-STRATEGY
        value: ant_path_matcher
      - name: PROMETHEUS_URL
        value: http://10.61.3.12:30090/
  frontend:
    repository: "harbor.xiilab.com:32443/uyuni/uyuni-frontend"
    imageTag: develop-df9b3ba
    service:
      type: NodePort
      port: 3000
      nodePort: 30080
    env:
      - name: KEYCLOAK_HOST
        value: https://10.61.3.8:30002
      - name: KEYCLOAK_REALME
        value: myrealm
      - name: KEYCLOAK_CLIENT_ID
        value: kubernetes-client
      - name: AUTH_CLIENT_SECRET
        value: 7bE2Oq2HyKrPsX49EXul0G48O4c4kkFv
      - name: NEXTAUTH_URL
        value: http://localhost:3000
      - name: NEXTAUTH_SECRET
        value: uuNj1L0Yg2xKcBPVp7yOVlm2nigL3hoHOzbwQXAwx1I=
      - name: NEXT_PUBLIC_API_URL
        value: http://localhost:4444/
