astrago:
  prometheus:
    host: http://10.61.3.12:30090
  keycloak:
    host: http://10.61.3.8:30001
    realm: myrealm
    client: kubernetes-client
    clientSecret: 7bE2Oq2HyKrPsX49EXul0G48O4c4kkFv
    nextauthUrl: http://10.61.3.12:30080
  mariadb:
    rootPassword: root
    database: astrago
    username: astrago
    password: xiirocks
    volume:
      volumeName: astra-mariadb-volume
      volumeSize: 8Gi
      volumeType: nfs
      nfs:
        server: 10.61.3.2
        path: /kube_storage/astra-mariadb-volume
  core:
    repository: "harbor.xiilab.com:32443/uyuni/server-core"
    imageTag: "develop-3042254"
  batch:
    repository: "harbor.xiilab.com:32443/uyuni/server-batch"
    imageTag: "develop-3042254"
  monitor:
    repository: "harbor.xiilab.com:32443/uyuni/server-monitor"
    imageTag: "develop-3042254"
  frontend:
    repository: "harbor.xiilab.com:32443/uyuni/uyuni-frontend"
    imageTag: develop-18c0bbb
    service:
      type: NodePort
      port: 3000
      nodePort: 30080
