astrago:
  prometheus:
    host: http://10.61.3.12:30090
  keycloak:
    host: http://10.61.3.8:30001
    realm: myrealm
    client: kubernetes-client
    clientSecret: 7bE2Oq2HyKrPsX49EXul0G48O4c4kkFv
    nextauthUrl: http://10.61.3.12:30080
  mariadb:
    rootPassword: root
    database: astrago
    username: astrago
    password: xiirocks
    volume:
      volumeName: astra-mariadb-volume
      volumeSize: 8Gi
      volumeType: nfs
      nfs:
        server: 10.61.3.2
        path: /kube_storage/astra-mariadb-volume
  core:
    #    repository: "harbor.xiilab.com:32443/uyuni/server-core"
    repository: xiilab/astrago-backend
    imageTag: "core-develop-f84df7f"
  batch:
    #    repository: "harbor.xiilab.com:32443/uyuni/server-batch"
    repository: xiilab/astrago-backend
    imageTag: "batch-develop-f84df7f"
  monitor:
    #    repository: "harbor.xiilab.com:32443/uyuni/server-monitor"
    repository: xiilab/astrago-backend
    imageTag: "monitor-develop-f84df7f"
  frontend:
    repository: "docker.io/xiilab/astrago-frontend"
    imageTag: develop-75babbd
    service:
      type: NodePort
      port: 3000
      nodePort: 30080
