keycloak:
  themeVersion: v1.0.13
  adminUser: admin
  adminPassword: xiirocks
  createVolume:
    enabled: true
    name: keycloak-volume
    size: 8Gi
    volumeType: nfs
    nfs:
      server: 10.61.3.2
      path: /kube_storage/develop-astrago-keycloak-volume
astrago:
  prometheus:
    host: http://10.61.3.12:30090
  keycloak:
    host: http://10.61.3.8:30001
    realm: myrealm
    client: kubernetes-client
    clientSecret: 7bE2Oq2HyKrPsX49EXul0G48O4c4kkFv
    nextauthUrl: http://10.61.3.12:30080
  log:
    createVolume:
      enabled: true
      name: astrago-workload-log
      size: 8Gi
      volumeType: nfs
      nfs:
        server: 10.61.3.2
        path: /kube_storage/astrago-log-volume
  mariadb:
    rootPassword: root
    database: astrago
    username: astrago
    password: xiirocks
    maxLifetime: :3595000
    volume:
      volumeName: astra-mariadb-volume
      volumeSize: 8Gi
      volumeType: nfs
      nfs:
        server: 10.61.3.2
        path: /kube_storage/astra-mariadb-volume
  core:
    repository: "harbor.xiilab.com:32443/uyuni/server-core"
    imageTag: "develop-5afb502"
  batch:
    repository: "harbor.xiilab.com:32443/uyuni/server-batch"
    imageTag: "develop-5afb502"
  monitor:
    repository: "harbor.xiilab.com:32443/uyuni/server-monitor"
    imageTag: "develop-5afb502"
  frontend:
    repository: "harbor.xiilab.com:32443/uyuni/uyuni-frontend"
    imageTag: develop-ede0178
    service:
      type: NodePort
      port: 3000
      nodePort: 30080
