# externalIP: 
externalIP: 10.61.3.12
# Volume Settings
nfs:
  enabled: true
  storageClassName: astrago-nfs-csi
  server: 10.61.3.2
  basePath: /kube_storage/develop-astrago
local:
  enabled: false
  storageClassName: astrago-local-storage
  nodeName:
  basePath:
# Keycloak Settings
keycloak:
  themeVersion: v1.1.3
  adminUser: admin
  adminPassword: xiirocks
  servicePort: 30001
# Astrago Settings
astrago:
  servicePort: 30080
  userInitPassword: astrago
  keycloak:
    realm: astrago
    client: astrago-client
    clientSecret: astragosecret
    userInitPassword: astrago
  mariadb:
    rootPassword: root
    username: astrago
    password: xiirocks
    maxLifetime: "3595000"
  core:
    repository: "harbor.xiilab.com:32443/astrago/core"
    imageTag: "dev-ac5d"
  batch:
    repository: "harbor.xiilab.com:32443/astrago/batch"
    imageTag: "dev-ac5d"
  monitor:
    repository: "harbor.xiilab.com:32443/astrago/monitor"
    imageTag: "dev-ac5d"
  frontend:
    repository: "harbor.xiilab.com:32443/astrago/frontend"
    imageTag: dev-9f62
