# externalIP: 
externalIP: 10.61.3.12
# Volume Settings
nfs:
  storageClassName: astrago-nfs-csi
  server: 10.61.3.2
  basePath: /kube_storage/develop-astrago
# Keycloak Settings
keycloak:
  adminUser: admin
  adminPassword: xiirocks
  servicePort: 30001
# Astrago Settings
astrago:
  proxyUrl:
  servicePort: 30080
  userInitPassword: astrago
  keycloak:
    externalKeycloakUrl: http://10.61.3.138:30001
    realm: astrago
    client: astrago-client
    clientSecret: astragosecret
    userInitPassword: astrago
  mariadb:
    rootPassword: root
    username: astrago
    password: xiirocks
    maxLifetime: "3595000"
  mongodb:
    url: mongodb://astrago:xiirocks@astrago-mongodb:27017/astrago?authSource=admin
  core:
    registry: "docker.io"
    repository: "xiilab/astrago"
    imageTag: "dev-3eff"
  batch:
    registry: "docker.io"
    repository: "xiilab/astrago"
    imageTag: "dev-3eff"
  monitor:
    registry: "docker.io"
    repository: "xiilab/astrago"
    imageTag: "dev-3eff"
  frontend:
    registry: "harbor.xiilab.com:32443"
    repository: "astrago/frontend"
    imageTag: dev-889b
  experiment:
    registry: "docker.io"
    repository: "xiilab/astrago"
    imageTag: "dev-3eff"
harbor:
  enabled: true    
offline:
  registry: # 192.168.56.11:35000
  httpServer: # http://192.168.56.11
