# externalIP: 
externalIP: 10.61.3.12
# Volume Settings
nfs:
  storageClassName: astrago-nfs-csi
  server: 10.61.3.2
  basePath: /kube_storage/develop-astrago

# GPU Session Monitoring Settings - Linear BE-102
gpu-session-monitoring:
  enabled: true
  collection:
    schedule: "*/1 * * * *"  # Every minute
    image:
      repository: busybox
      tag: "1.35"
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 32Mi
  prometheus:
    serverService: prometheus-kube-prometheus-prometheus.prometheus.svc:9090
  gpu:
    count: 4
    devices: [0, 1, 2, 3]
  nodeSelector:
    nvidia.com/gpu.present: "true"
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule

# Keycloak Settings
keycloak:
  adminUser: admin
  adminPassword: xiirocks
  servicePort: 30001
# Astrago Settings
astrago:
  proxyUrl: http://10.61.3.12:30080
  servicePort: 30080
  userInitPassword: astrago
  keycloak:
    externalKeycloakUrl: http://10.61.3.12:30001/auth
    realm: astrago
    client: astrago-client
    clientSecret: astragosecret
    userInitPassword: astrago
  mariadb:
    rootPassword: root
    username: astrago
    password: xiirocks
    maxLifetime: "3595000"
  mongodb:
    url: mongodb://astrago:xiirocks@astrago-mongodb:27017/astrago?authSource=admin
  core:
    registry: "harbor.xiilab.com:32080"
    repository: "astrago/core"
    imageTag: "dev-3eff"
  batch:
    registry: "harbor.xiilab.com:32080"
    repository: "astrago/batch"
    imageTag: "dev-3eff"
  monitor:
    registry: "harbor.xiilab.com:32080"
    repository: "astrago/monitor"
    imageTag: "dev-3eff"
  frontend:
    registry: "harbor.xiilab.com:32080"
    repository: "astrago/frontend"
    imageTag: dev-889b
  experiment:
    registry: "harbor.xiilab.com:32080"
    repository: "astrago/experiment"
    imageTag: "dev-3eff"
  oneview:
    enabled: true
harbor:
  enabled: true    
offline:
  registry: # 192.168.56.11:35000
  httpServer: # http://192.168.56.11
