common:
  ingress:
    domain: "default.com"

uyuni:
  nodePort: 30100
  keycloakUrl: http://192.168.1.235:30051/auth

#  frontend:
#    repository: xiilab/uyuni-suite-frontend
#    imageTag: 0.4.84-stag

  core:
    repository: xiilab/uyuni-backend-core
    imageTag: master

  batch:
    repository: xiilab/uyuni-backend-batch
    imageTag: master

  monitor:
    repository: xiilab/uyuni-backend-monitor
    imageTag: master
