apiVersion: v1
kind: Secret
metadata:
  name: astrago-staging-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    astrago.io/environment: dev12
    astrago.io/branch: stabilize-1.0
type: Opaque
stringData:
  name: astrago-dev12-cluster
  server: https://10.61.3.12:6443
  config: |
    {
      "bearerToken": "",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "",
        "certData": "",
        "keyData": ""
      }
    }