common:
  ingress:
    domain: "default.com"

nfs:
  server: 192.168.2.39
  share: /kube-storage

uyuni:
  nodePort: 30100
  keycloakUrl: http://192.168.1.235:30051/auth
  core:
    repository: xiilab/uyuni-backend-core
    imageTag: master

  batch:
    repository: xiilab/uyuni-backend-batch
    imageTag: master

  monitor:
    repository: xiilab/uyuni-backend-monitor
    imageTag: master

  frontend:
    repository: xiilab/uyuni-frontend
    imageTag: master