# externalIP: 
externalIP:

# Volume Settings
nfs:
  enabled: false
  storageClassName: astrago-nfs-csi
  server:
  basePath:
local:
  enabled: false
  storageClassName: astrago-local-storage
  nodeName:
  basePath:

# Keycloak Settings
keycloak:
  themeVersion: v1.0.13
  adminUser: admin
  adminPassword: xiirocks
  servicePort: 30001

# Astrago Settings
astrago:
  servicePort: 30080
  userInitPassword: astrago
  keycloak:
    realm: astrago
    client: astrago-client
    clientSecret: astragosecret
    userInitPassword: astrago
  mariadb:
    rootPassword: root
    username: astrago
    password: xiirocks
    maxLifetime: "3595000"
  core:
    repository: "harbor.xiilab.com:32443/uyuni/server-core"
    imageTag: "develop-07c21f4"
  batch:
    repository: "harbor.xiilab.com:32443/uyuni/server-batch"
    imageTag: "develop-07c21f4"
  monitor:
    repository: "harbor.xiilab.com:32443/uyuni/server-monitor"
    imageTag: "develop-07c21f4"
  frontend:
    repository: "harbor.xiilab.com:32443/uyuni/uyuni-frontend"
    imageTag: develop-e2a975b
